/*
Tyk Gateway API

Testing KeysAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apim

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/TykTechnologies/gateway-sdk/pkg/apim"
)

func Test_apim_KeysAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test KeysAPIService AddKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.KeysAPI.AddKey(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KeysAPIService CreateCustomKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyID string

		resp, httpRes, err := apiClient.KeysAPI.CreateCustomKey(context.Background(), keyID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KeysAPIService DeleteKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyID string

		resp, httpRes, err := apiClient.KeysAPI.DeleteKey(context.Background(), keyID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KeysAPIService GetKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyID string

		resp, httpRes, err := apiClient.KeysAPI.GetKey(context.Background(), keyID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KeysAPIService ListKeys", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.KeysAPI.ListKeys(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KeysAPIService UpdateKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyID string

		resp, httpRes, err := apiClient.KeysAPI.UpdateKey(context.Background(), keyID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
