/*
Tyk Gateway API

Testing OrganisationQuotasAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package apim

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/TykTechnologies/gateway-sdk/pkg/apim"
)

func Test_apim_OrganisationQuotasAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OrganisationQuotasAPIService AddOrgKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyID string

		resp, httpRes, err := apiClient.OrganisationQuotasAPI.AddOrgKey(context.Background(), keyID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganisationQuotasAPIService DeleteOrgKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyID string

		resp, httpRes, err := apiClient.OrganisationQuotasAPI.DeleteOrgKey(context.Background(), keyID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganisationQuotasAPIService GetOrgKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyID string

		resp, httpRes, err := apiClient.OrganisationQuotasAPI.GetOrgKey(context.Background(), keyID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganisationQuotasAPIService ListOrgKeys", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OrganisationQuotasAPI.ListOrgKeys(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganisationQuotasAPIService UpdateOrgKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyID string

		resp, httpRes, err := apiClient.OrganisationQuotasAPI.UpdateOrgKey(context.Background(), keyID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
