/*
Tyk Gateway API

 The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway

API version: 5.2.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apim

import (
	"encoding/json"
)

// checks if the APICertificateStatusMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &APICertificateStatusMessage{}

// APICertificateStatusMessage struct for APICertificateStatusMessage
type APICertificateStatusMessage struct {
	Id *string `json:"id,omitempty"`
	Message *string `json:"message,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewAPICertificateStatusMessage instantiates a new APICertificateStatusMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPICertificateStatusMessage() *APICertificateStatusMessage {
	this := APICertificateStatusMessage{}
	return &this
}

// NewAPICertificateStatusMessageWithDefaults instantiates a new APICertificateStatusMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPICertificateStatusMessageWithDefaults() *APICertificateStatusMessage {
	this := APICertificateStatusMessage{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *APICertificateStatusMessage) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APICertificateStatusMessage) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *APICertificateStatusMessage) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *APICertificateStatusMessage) SetId(v string) {
	o.Id = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *APICertificateStatusMessage) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APICertificateStatusMessage) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *APICertificateStatusMessage) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *APICertificateStatusMessage) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *APICertificateStatusMessage) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APICertificateStatusMessage) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *APICertificateStatusMessage) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *APICertificateStatusMessage) SetStatus(v string) {
	o.Status = &v
}

func (o APICertificateStatusMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o APICertificateStatusMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableAPICertificateStatusMessage struct {
	value *APICertificateStatusMessage
	isSet bool
}

func (v NullableAPICertificateStatusMessage) Get() *APICertificateStatusMessage {
	return v.value
}

func (v *NullableAPICertificateStatusMessage) Set(val *APICertificateStatusMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableAPICertificateStatusMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableAPICertificateStatusMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPICertificateStatusMessage(val *APICertificateStatusMessage) *NullableAPICertificateStatusMessage {
	return &NullableAPICertificateStatusMessage{value: val, isSet: true}
}

func (v NullableAPICertificateStatusMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPICertificateStatusMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


