/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation). * Managing and listing policies. * Managing and listing API Definitions (only when not using the Tyk Dashboard). * Hot reloads / reloading a cluster configuration. * OAuth client creation (only when not using the Tyk Dashboard).  In order to use the Gateway API, you'll need to set the **secret** parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  **x-tyk-authorization: <your-secret>*** <br/>  <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 5.7.1
Contact: support@tyk.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apim

import (
	"encoding/json"
)

// checks if the IDExtractor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IDExtractor{}

// IDExtractor struct for IDExtractor
type IDExtractor struct {
	Config  *IDExtractorConfig `json:"config,omitempty"`
	Enabled *bool              `json:"enabled,omitempty"`
	Source  *string            `json:"source,omitempty"`
	With    *string            `json:"with,omitempty"`
}

// NewIDExtractor instantiates a new IDExtractor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIDExtractor() *IDExtractor {
	this := IDExtractor{}
	return &this
}

// NewIDExtractorWithDefaults instantiates a new IDExtractor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIDExtractorWithDefaults() *IDExtractor {
	this := IDExtractor{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *IDExtractor) GetConfig() IDExtractorConfig {
	if o == nil || IsNil(o.Config) {
		var ret IDExtractorConfig
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IDExtractor) GetConfigOk() (*IDExtractorConfig, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *IDExtractor) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given IDExtractorConfig and assigns it to the Config field.
func (o *IDExtractor) SetConfig(v IDExtractorConfig) {
	o.Config = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *IDExtractor) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IDExtractor) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *IDExtractor) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *IDExtractor) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *IDExtractor) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IDExtractor) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *IDExtractor) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *IDExtractor) SetSource(v string) {
	o.Source = &v
}

// GetWith returns the With field value if set, zero value otherwise.
func (o *IDExtractor) GetWith() string {
	if o == nil || IsNil(o.With) {
		var ret string
		return ret
	}
	return *o.With
}

// GetWithOk returns a tuple with the With field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IDExtractor) GetWithOk() (*string, bool) {
	if o == nil || IsNil(o.With) {
		return nil, false
	}
	return o.With, true
}

// HasWith returns a boolean if a field has been set.
func (o *IDExtractor) HasWith() bool {
	if o != nil && !IsNil(o.With) {
		return true
	}

	return false
}

// SetWith gets a reference to the given string and assigns it to the With field.
func (o *IDExtractor) SetWith(v string) {
	o.With = &v
}

func (o IDExtractor) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IDExtractor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.With) {
		toSerialize["with"] = o.With
	}
	return toSerialize, nil
}

type NullableIDExtractor struct {
	value *IDExtractor
	isSet bool
}

func (v NullableIDExtractor) Get() *IDExtractor {
	return v.value
}

func (v *NullableIDExtractor) Set(val *IDExtractor) {
	v.value = val
	v.isSet = true
}

func (v NullableIDExtractor) IsSet() bool {
	return v.isSet
}

func (v *NullableIDExtractor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIDExtractor(val *IDExtractor) *NullableIDExtractor {
	return &NullableIDExtractor{value: val, isSet: true}
}

func (v NullableIDExtractor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIDExtractor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
