/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation). * Managing and listing policies. * Managing and listing API Definitions (only when not using the Tyk Dashboard). * Hot reloads / reloading a cluster configuration. * OAuth client creation (only when not using the Tyk Dashboard).  In order to use the Gateway API, you'll need to set the **secret** parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  **x-tyk-authorization: <your-secret>*** <br/>  <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 5.7.1
Contact: support@tyk.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apim

import (
	"encoding/json"
)

// checks if the ListenPath type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListenPath{}

// ListenPath struct for ListenPath
type ListenPath struct {
	Strip *bool   `json:"strip,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewListenPath instantiates a new ListenPath object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListenPath() *ListenPath {
	this := ListenPath{}
	return &this
}

// NewListenPathWithDefaults instantiates a new ListenPath object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListenPathWithDefaults() *ListenPath {
	this := ListenPath{}
	return &this
}

// GetStrip returns the Strip field value if set, zero value otherwise.
func (o *ListenPath) GetStrip() bool {
	if o == nil || IsNil(o.Strip) {
		var ret bool
		return ret
	}
	return *o.Strip
}

// GetStripOk returns a tuple with the Strip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListenPath) GetStripOk() (*bool, bool) {
	if o == nil || IsNil(o.Strip) {
		return nil, false
	}
	return o.Strip, true
}

// HasStrip returns a boolean if a field has been set.
func (o *ListenPath) HasStrip() bool {
	if o != nil && !IsNil(o.Strip) {
		return true
	}

	return false
}

// SetStrip gets a reference to the given bool and assigns it to the Strip field.
func (o *ListenPath) SetStrip(v bool) {
	o.Strip = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ListenPath) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListenPath) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ListenPath) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ListenPath) SetValue(v string) {
	o.Value = &v
}

func (o ListenPath) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListenPath) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Strip) {
		toSerialize["strip"] = o.Strip
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableListenPath struct {
	value *ListenPath
	isSet bool
}

func (v NullableListenPath) Get() *ListenPath {
	return v.value
}

func (v *NullableListenPath) Set(val *ListenPath) {
	v.value = val
	v.isSet = true
}

func (v NullableListenPath) IsSet() bool {
	return v.isSet
}

func (v *NullableListenPath) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListenPath(val *ListenPath) *NullableListenPath {
	return &NullableListenPath{value: val, isSet: true}
}

func (v NullableListenPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListenPath) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
