/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation). * Managing and listing policies. * Managing and listing API Definitions (only when not using the Tyk Dashboard). * Hot reloads / reloading a cluster configuration. * OAuth client creation (only when not using the Tyk Dashboard).  In order to use the Gateway API, you'll need to set the **secret** parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  **x-tyk-authorization: <your-secret>*** <br/>  <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 5.7.1
Contact: support@tyk.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apim

import (
	"encoding/json"
)

// checks if the CertificatePinning type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificatePinning{}

// CertificatePinning struct for CertificatePinning
type CertificatePinning struct {
	DomainToPublicKeysMapping []PinnedPublicKey `json:"domainToPublicKeysMapping,omitempty"`
	Enabled                   *bool             `json:"enabled,omitempty"`
}

// NewCertificatePinning instantiates a new CertificatePinning object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificatePinning() *CertificatePinning {
	this := CertificatePinning{}
	return &this
}

// NewCertificatePinningWithDefaults instantiates a new CertificatePinning object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificatePinningWithDefaults() *CertificatePinning {
	this := CertificatePinning{}
	return &this
}

// GetDomainToPublicKeysMapping returns the DomainToPublicKeysMapping field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CertificatePinning) GetDomainToPublicKeysMapping() []PinnedPublicKey {
	if o == nil {
		var ret []PinnedPublicKey
		return ret
	}
	return o.DomainToPublicKeysMapping
}

// GetDomainToPublicKeysMappingOk returns a tuple with the DomainToPublicKeysMapping field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CertificatePinning) GetDomainToPublicKeysMappingOk() ([]PinnedPublicKey, bool) {
	if o == nil || IsNil(o.DomainToPublicKeysMapping) {
		return nil, false
	}
	return o.DomainToPublicKeysMapping, true
}

// HasDomainToPublicKeysMapping returns a boolean if a field has been set.
func (o *CertificatePinning) HasDomainToPublicKeysMapping() bool {
	if o != nil && !IsNil(o.DomainToPublicKeysMapping) {
		return true
	}

	return false
}

// SetDomainToPublicKeysMapping gets a reference to the given []PinnedPublicKey and assigns it to the DomainToPublicKeysMapping field.
func (o *CertificatePinning) SetDomainToPublicKeysMapping(v []PinnedPublicKey) {
	o.DomainToPublicKeysMapping = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CertificatePinning) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificatePinning) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CertificatePinning) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CertificatePinning) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o CertificatePinning) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificatePinning) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DomainToPublicKeysMapping != nil {
		toSerialize["domainToPublicKeysMapping"] = o.DomainToPublicKeysMapping
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullableCertificatePinning struct {
	value *CertificatePinning
	isSet bool
}

func (v NullableCertificatePinning) Get() *CertificatePinning {
	return v.value
}

func (v *NullableCertificatePinning) Set(val *CertificatePinning) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificatePinning) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificatePinning) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificatePinning(val *CertificatePinning) *NullableCertificatePinning {
	return &NullableCertificatePinning{value: val, isSet: true}
}

func (v NullableCertificatePinning) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificatePinning) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
