/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation). * Managing and listing policies. * Managing and listing API Definitions (only when not using the Tyk Dashboard). * Hot reloads / reloading a cluster configuration. * OAuth client creation (only when not using the Tyk Dashboard).  In order to use the Gateway API, you'll need to set the **secret** parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  **x-tyk-authorization: <your-secret>*** <br/>  <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 5.7.1
Contact: support@tyk.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apim

import (
	"encoding/json"
)

// checks if the RequestSizeLimit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestSizeLimit{}

// RequestSizeLimit struct for RequestSizeLimit
type RequestSizeLimit struct {
	Enabled *bool  `json:"enabled,omitempty"`
	Value   *int32 `json:"value,omitempty"`
}

// NewRequestSizeLimit instantiates a new RequestSizeLimit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestSizeLimit() *RequestSizeLimit {
	this := RequestSizeLimit{}
	return &this
}

// NewRequestSizeLimitWithDefaults instantiates a new RequestSizeLimit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestSizeLimitWithDefaults() *RequestSizeLimit {
	this := RequestSizeLimit{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *RequestSizeLimit) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestSizeLimit) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *RequestSizeLimit) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *RequestSizeLimit) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *RequestSizeLimit) GetValue() int32 {
	if o == nil || IsNil(o.Value) {
		var ret int32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestSizeLimit) GetValueOk() (*int32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *RequestSizeLimit) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given int32 and assigns it to the Value field.
func (o *RequestSizeLimit) SetValue(v int32) {
	o.Value = &v
}

func (o RequestSizeLimit) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestSizeLimit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableRequestSizeLimit struct {
	value *RequestSizeLimit
	isSet bool
}

func (v NullableRequestSizeLimit) Get() *RequestSizeLimit {
	return v.value
}

func (v *NullableRequestSizeLimit) Set(val *RequestSizeLimit) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestSizeLimit) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestSizeLimit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestSizeLimit(val *RequestSizeLimit) *NullableRequestSizeLimit {
	return &NullableRequestSizeLimit{value: val, isSet: true}
}

func (v NullableRequestSizeLimit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestSizeLimit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
