/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 4.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apim

import (
	"encoding/json"
)

// checks if the CircuitBreakerMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CircuitBreakerMeta{}

// CircuitBreakerMeta struct for CircuitBreakerMeta
type CircuitBreakerMeta struct {
	Method *string `json:"method,omitempty"`
	Path *string `json:"path,omitempty"`
	ReturnToServiceAfter *int64 `json:"return_to_service_after,omitempty"`
	Samples *int64 `json:"samples,omitempty"`
	ThresholdPercent *float64 `json:"threshold_percent,omitempty"`
}

// NewCircuitBreakerMeta instantiates a new CircuitBreakerMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCircuitBreakerMeta() *CircuitBreakerMeta {
	this := CircuitBreakerMeta{}
	return &this
}

// NewCircuitBreakerMetaWithDefaults instantiates a new CircuitBreakerMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCircuitBreakerMetaWithDefaults() *CircuitBreakerMeta {
	this := CircuitBreakerMeta{}
	return &this
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *CircuitBreakerMeta) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CircuitBreakerMeta) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *CircuitBreakerMeta) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *CircuitBreakerMeta) SetMethod(v string) {
	o.Method = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *CircuitBreakerMeta) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CircuitBreakerMeta) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *CircuitBreakerMeta) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *CircuitBreakerMeta) SetPath(v string) {
	o.Path = &v
}

// GetReturnToServiceAfter returns the ReturnToServiceAfter field value if set, zero value otherwise.
func (o *CircuitBreakerMeta) GetReturnToServiceAfter() int64 {
	if o == nil || IsNil(o.ReturnToServiceAfter) {
		var ret int64
		return ret
	}
	return *o.ReturnToServiceAfter
}

// GetReturnToServiceAfterOk returns a tuple with the ReturnToServiceAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CircuitBreakerMeta) GetReturnToServiceAfterOk() (*int64, bool) {
	if o == nil || IsNil(o.ReturnToServiceAfter) {
		return nil, false
	}
	return o.ReturnToServiceAfter, true
}

// HasReturnToServiceAfter returns a boolean if a field has been set.
func (o *CircuitBreakerMeta) HasReturnToServiceAfter() bool {
	if o != nil && !IsNil(o.ReturnToServiceAfter) {
		return true
	}

	return false
}

// SetReturnToServiceAfter gets a reference to the given int64 and assigns it to the ReturnToServiceAfter field.
func (o *CircuitBreakerMeta) SetReturnToServiceAfter(v int64) {
	o.ReturnToServiceAfter = &v
}

// GetSamples returns the Samples field value if set, zero value otherwise.
func (o *CircuitBreakerMeta) GetSamples() int64 {
	if o == nil || IsNil(o.Samples) {
		var ret int64
		return ret
	}
	return *o.Samples
}

// GetSamplesOk returns a tuple with the Samples field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CircuitBreakerMeta) GetSamplesOk() (*int64, bool) {
	if o == nil || IsNil(o.Samples) {
		return nil, false
	}
	return o.Samples, true
}

// HasSamples returns a boolean if a field has been set.
func (o *CircuitBreakerMeta) HasSamples() bool {
	if o != nil && !IsNil(o.Samples) {
		return true
	}

	return false
}

// SetSamples gets a reference to the given int64 and assigns it to the Samples field.
func (o *CircuitBreakerMeta) SetSamples(v int64) {
	o.Samples = &v
}

// GetThresholdPercent returns the ThresholdPercent field value if set, zero value otherwise.
func (o *CircuitBreakerMeta) GetThresholdPercent() float64 {
	if o == nil || IsNil(o.ThresholdPercent) {
		var ret float64
		return ret
	}
	return *o.ThresholdPercent
}

// GetThresholdPercentOk returns a tuple with the ThresholdPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CircuitBreakerMeta) GetThresholdPercentOk() (*float64, bool) {
	if o == nil || IsNil(o.ThresholdPercent) {
		return nil, false
	}
	return o.ThresholdPercent, true
}

// HasThresholdPercent returns a boolean if a field has been set.
func (o *CircuitBreakerMeta) HasThresholdPercent() bool {
	if o != nil && !IsNil(o.ThresholdPercent) {
		return true
	}

	return false
}

// SetThresholdPercent gets a reference to the given float64 and assigns it to the ThresholdPercent field.
func (o *CircuitBreakerMeta) SetThresholdPercent(v float64) {
	o.ThresholdPercent = &v
}

func (o CircuitBreakerMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CircuitBreakerMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.ReturnToServiceAfter) {
		toSerialize["return_to_service_after"] = o.ReturnToServiceAfter
	}
	if !IsNil(o.Samples) {
		toSerialize["samples"] = o.Samples
	}
	if !IsNil(o.ThresholdPercent) {
		toSerialize["threshold_percent"] = o.ThresholdPercent
	}
	return toSerialize, nil
}

type NullableCircuitBreakerMeta struct {
	value *CircuitBreakerMeta
	isSet bool
}

func (v NullableCircuitBreakerMeta) Get() *CircuitBreakerMeta {
	return v.value
}

func (v *NullableCircuitBreakerMeta) Set(val *CircuitBreakerMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableCircuitBreakerMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableCircuitBreakerMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCircuitBreakerMeta(val *CircuitBreakerMeta) *NullableCircuitBreakerMeta {
	return &NullableCircuitBreakerMeta{value: val, isSet: true}
}

func (v NullableCircuitBreakerMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCircuitBreakerMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


