/*
Tyk Gateway API

 The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway

API version: 5.2.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apim

import (
	"encoding/json"
)

// checks if the GraphQLPlayground type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GraphQLPlayground{}

// GraphQLPlayground struct for GraphQLPlayground
type GraphQLPlayground struct {
	Enabled *bool `json:"enabled,omitempty"`
	Path *string `json:"path,omitempty"`
}

// NewGraphQLPlayground instantiates a new GraphQLPlayground object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGraphQLPlayground() *GraphQLPlayground {
	this := GraphQLPlayground{}
	return &this
}

// NewGraphQLPlaygroundWithDefaults instantiates a new GraphQLPlayground object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGraphQLPlaygroundWithDefaults() *GraphQLPlayground {
	this := GraphQLPlayground{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *GraphQLPlayground) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphQLPlayground) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *GraphQLPlayground) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *GraphQLPlayground) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *GraphQLPlayground) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphQLPlayground) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *GraphQLPlayground) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *GraphQLPlayground) SetPath(v string) {
	o.Path = &v
}

func (o GraphQLPlayground) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GraphQLPlayground) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	return toSerialize, nil
}

type NullableGraphQLPlayground struct {
	value *GraphQLPlayground
	isSet bool
}

func (v NullableGraphQLPlayground) Get() *GraphQLPlayground {
	return v.value
}

func (v *NullableGraphQLPlayground) Set(val *GraphQLPlayground) {
	v.value = val
	v.isSet = true
}

func (v NullableGraphQLPlayground) IsSet() bool {
	return v.isSet
}

func (v *NullableGraphQLPlayground) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGraphQLPlayground(val *GraphQLPlayground) *NullableGraphQLPlayground {
	return &NullableGraphQLPlayground{value: val, isSet: true}
}

func (v NullableGraphQLPlayground) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGraphQLPlayground) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


