/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation). * Managing and listing policies. * Managing and listing API Definitions (only when not using the Tyk Dashboard). * Hot reloads / reloading a cluster configuration. * OAuth client creation (only when not using the Tyk Dashboard).  In order to use the Gateway API, you'll need to set the **secret** parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  **x-tyk-authorization: <your-secret>*** <br/>  <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 5.7.1
Contact: support@tyk.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apim

import (
	"encoding/json"
)

// checks if the GraphQLProxyFeaturesConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GraphQLProxyFeaturesConfig{}

// GraphQLProxyFeaturesConfig struct for GraphQLProxyFeaturesConfig
type GraphQLProxyFeaturesConfig struct {
	UseImmutableHeaders *bool `json:"use_immutable_headers,omitempty"`
}

// NewGraphQLProxyFeaturesConfig instantiates a new GraphQLProxyFeaturesConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGraphQLProxyFeaturesConfig() *GraphQLProxyFeaturesConfig {
	this := GraphQLProxyFeaturesConfig{}
	return &this
}

// NewGraphQLProxyFeaturesConfigWithDefaults instantiates a new GraphQLProxyFeaturesConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGraphQLProxyFeaturesConfigWithDefaults() *GraphQLProxyFeaturesConfig {
	this := GraphQLProxyFeaturesConfig{}
	return &this
}

// GetUseImmutableHeaders returns the UseImmutableHeaders field value if set, zero value otherwise.
func (o *GraphQLProxyFeaturesConfig) GetUseImmutableHeaders() bool {
	if o == nil || IsNil(o.UseImmutableHeaders) {
		var ret bool
		return ret
	}
	return *o.UseImmutableHeaders
}

// GetUseImmutableHeadersOk returns a tuple with the UseImmutableHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphQLProxyFeaturesConfig) GetUseImmutableHeadersOk() (*bool, bool) {
	if o == nil || IsNil(o.UseImmutableHeaders) {
		return nil, false
	}
	return o.UseImmutableHeaders, true
}

// HasUseImmutableHeaders returns a boolean if a field has been set.
func (o *GraphQLProxyFeaturesConfig) HasUseImmutableHeaders() bool {
	if o != nil && !IsNil(o.UseImmutableHeaders) {
		return true
	}

	return false
}

// SetUseImmutableHeaders gets a reference to the given bool and assigns it to the UseImmutableHeaders field.
func (o *GraphQLProxyFeaturesConfig) SetUseImmutableHeaders(v bool) {
	o.UseImmutableHeaders = &v
}

func (o GraphQLProxyFeaturesConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GraphQLProxyFeaturesConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UseImmutableHeaders) {
		toSerialize["use_immutable_headers"] = o.UseImmutableHeaders
	}
	return toSerialize, nil
}

type NullableGraphQLProxyFeaturesConfig struct {
	value *GraphQLProxyFeaturesConfig
	isSet bool
}

func (v NullableGraphQLProxyFeaturesConfig) Get() *GraphQLProxyFeaturesConfig {
	return v.value
}

func (v *NullableGraphQLProxyFeaturesConfig) Set(val *GraphQLProxyFeaturesConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableGraphQLProxyFeaturesConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableGraphQLProxyFeaturesConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGraphQLProxyFeaturesConfig(val *GraphQLProxyFeaturesConfig) *NullableGraphQLProxyFeaturesConfig {
	return &NullableGraphQLProxyFeaturesConfig{value: val, isSet: true}
}

func (v NullableGraphQLProxyFeaturesConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGraphQLProxyFeaturesConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
