/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation). * Managing and listing policies. * Managing and listing API Definitions (only when not using the Tyk Dashboard). * Hot reloads / reloading a cluster configuration. * OAuth client creation (only when not using the Tyk Dashboard).  In order to use the Gateway API, you'll need to set the **secret** parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  **x-tyk-authorization: <your-secret>*** <br/>  <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 5.7.1
Contact: support@tyk.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apim

import (
	"encoding/json"
)

// checks if the GraphqlType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GraphqlType{}

// GraphqlType struct for GraphqlType
type GraphqlType struct {
	Fields []string `json:"fields,omitempty"`
	Name   *string  `json:"name,omitempty"`
}

// NewGraphqlType instantiates a new GraphqlType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGraphqlType() *GraphqlType {
	this := GraphqlType{}
	return &this
}

// NewGraphqlTypeWithDefaults instantiates a new GraphqlType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGraphqlTypeWithDefaults() *GraphqlType {
	this := GraphqlType{}
	return &this
}

// GetFields returns the Fields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GraphqlType) GetFields() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GraphqlType) GetFieldsOk() ([]string, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *GraphqlType) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []string and assigns it to the Fields field.
func (o *GraphqlType) SetFields(v []string) {
	o.Fields = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GraphqlType) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphqlType) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GraphqlType) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GraphqlType) SetName(v string) {
	o.Name = &v
}

func (o GraphqlType) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GraphqlType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Fields != nil {
		toSerialize["fields"] = o.Fields
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableGraphqlType struct {
	value *GraphqlType
	isSet bool
}

func (v NullableGraphqlType) Get() *GraphqlType {
	return v.value
}

func (v *NullableGraphqlType) Set(val *GraphqlType) {
	v.value = val
	v.isSet = true
}

func (v NullableGraphqlType) IsSet() bool {
	return v.isSet
}

func (v *NullableGraphqlType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGraphqlType(val *GraphqlType) *NullableGraphqlType {
	return &NullableGraphqlType{value: val, isSet: true}
}

func (v NullableGraphqlType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGraphqlType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
