/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation). * Managing and listing policies. * Managing and listing API Definitions (only when not using the Tyk Dashboard). * Hot reloads / reloading a cluster configuration. * OAuth client creation (only when not using the Tyk Dashboard).  In order to use the Gateway API, you'll need to set the **secret** parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  **x-tyk-authorization: <your-secret>*** <br/>  <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 5.7.1
Contact: support@tyk.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apim

import (
	"encoding/json"
)

// checks if the TransformRequestMethod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransformRequestMethod{}

// TransformRequestMethod struct for TransformRequestMethod
type TransformRequestMethod struct {
	Enabled  *bool   `json:"enabled,omitempty"`
	ToMethod *string `json:"toMethod,omitempty"`
}

// NewTransformRequestMethod instantiates a new TransformRequestMethod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransformRequestMethod() *TransformRequestMethod {
	this := TransformRequestMethod{}
	return &this
}

// NewTransformRequestMethodWithDefaults instantiates a new TransformRequestMethod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransformRequestMethodWithDefaults() *TransformRequestMethod {
	this := TransformRequestMethod{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *TransformRequestMethod) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransformRequestMethod) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *TransformRequestMethod) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *TransformRequestMethod) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetToMethod returns the ToMethod field value if set, zero value otherwise.
func (o *TransformRequestMethod) GetToMethod() string {
	if o == nil || IsNil(o.ToMethod) {
		var ret string
		return ret
	}
	return *o.ToMethod
}

// GetToMethodOk returns a tuple with the ToMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransformRequestMethod) GetToMethodOk() (*string, bool) {
	if o == nil || IsNil(o.ToMethod) {
		return nil, false
	}
	return o.ToMethod, true
}

// HasToMethod returns a boolean if a field has been set.
func (o *TransformRequestMethod) HasToMethod() bool {
	if o != nil && !IsNil(o.ToMethod) {
		return true
	}

	return false
}

// SetToMethod gets a reference to the given string and assigns it to the ToMethod field.
func (o *TransformRequestMethod) SetToMethod(v string) {
	o.ToMethod = &v
}

func (o TransformRequestMethod) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransformRequestMethod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.ToMethod) {
		toSerialize["toMethod"] = o.ToMethod
	}
	return toSerialize, nil
}

type NullableTransformRequestMethod struct {
	value *TransformRequestMethod
	isSet bool
}

func (v NullableTransformRequestMethod) Get() *TransformRequestMethod {
	return v.value
}

func (v *NullableTransformRequestMethod) Set(val *TransformRequestMethod) {
	v.value = val
	v.isSet = true
}

func (v NullableTransformRequestMethod) IsSet() bool {
	return v.isSet
}

func (v *NullableTransformRequestMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransformRequestMethod(val *TransformRequestMethod) *NullableTransformRequestMethod {
	return &NullableTransformRequestMethod{value: val, isSet: true}
}

func (v NullableTransformRequestMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransformRequestMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
