/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 4.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apim

import (
	"encoding/json"
)

// OpenIDOptionsModel struct for OpenIDOptionsModel
type OpenIDOptionsModel struct {
	Providers []OIDProviderConfigModelModel `json:"providers,omitempty"`
	SegregateByClient *bool `json:"segregate_by_client,omitempty"`
}

// NewOpenIDOptionsModel instantiates a new OpenIDOptionsModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenIDOptionsModel() *OpenIDOptionsModel {
	this := OpenIDOptionsModel{}
	return &this
}

// NewOpenIDOptionsModelWithDefaults instantiates a new OpenIDOptionsModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenIDOptionsModelWithDefaults() *OpenIDOptionsModel {
	this := OpenIDOptionsModel{}
	return &this
}

// GetProviders returns the Providers field value if set, zero value otherwise.
func (o *OpenIDOptionsModel) GetProviders() []OIDProviderConfigModelModel {
	if o == nil || o.Providers == nil {
		var ret []OIDProviderConfigModelModel
		return ret
	}
	return o.Providers
}

// GetProvidersOk returns a tuple with the Providers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenIDOptionsModel) GetProvidersOk() ([]OIDProviderConfigModelModel, bool) {
	if o == nil || o.Providers == nil {
		return nil, false
	}
	return o.Providers, true
}

// HasProviders returns a boolean if a field has been set.
func (o *OpenIDOptionsModel) HasProviders() bool {
	if o != nil && o.Providers != nil {
		return true
	}

	return false
}

// SetProviders gets a reference to the given []OIDProviderConfigModelModel and assigns it to the Providers field.
func (o *OpenIDOptionsModel) SetProviders(v []OIDProviderConfigModelModel) {
	o.Providers = v
}

// GetSegregateByClient returns the SegregateByClient field value if set, zero value otherwise.
func (o *OpenIDOptionsModel) GetSegregateByClient() bool {
	if o == nil || o.SegregateByClient == nil {
		var ret bool
		return ret
	}
	return *o.SegregateByClient
}

// GetSegregateByClientOk returns a tuple with the SegregateByClient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenIDOptionsModel) GetSegregateByClientOk() (*bool, bool) {
	if o == nil || o.SegregateByClient == nil {
		return nil, false
	}
	return o.SegregateByClient, true
}

// HasSegregateByClient returns a boolean if a field has been set.
func (o *OpenIDOptionsModel) HasSegregateByClient() bool {
	if o != nil && o.SegregateByClient != nil {
		return true
	}

	return false
}

// SetSegregateByClient gets a reference to the given bool and assigns it to the SegregateByClient field.
func (o *OpenIDOptionsModel) SetSegregateByClient(v bool) {
	o.SegregateByClient = &v
}

func (o OpenIDOptionsModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Providers != nil {
		toSerialize["providers"] = o.Providers
	}
	if o.SegregateByClient != nil {
		toSerialize["segregate_by_client"] = o.SegregateByClient
	}
	return json.Marshal(toSerialize)
}

type NullableOpenIDOptionsModel struct {
	value *OpenIDOptionsModel
	isSet bool
}

func (v NullableOpenIDOptionsModel) Get() *OpenIDOptionsModel {
	return v.value
}

func (v *NullableOpenIDOptionsModel) Set(val *OpenIDOptionsModel) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenIDOptionsModel) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenIDOptionsModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenIDOptionsModel(val *OpenIDOptionsModel) *NullableOpenIDOptionsModel {
	return &NullableOpenIDOptionsModel{value: val, isSet: true}
}

func (v NullableOpenIDOptionsModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenIDOptionsModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


