/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 4.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apim

import (
	"encoding/json"
)

// APIDefinitionModel struct for APIDefinitionModel
type APIDefinitionModel struct {
	Tags []string `json:"tags,omitempty"`
	CORS *APIDefinitionCORSModel `json:"CORS,omitempty"`
	Active *bool `json:"active,omitempty"`
	AllowedIps []string `json:"allowed_ips,omitempty"`
	ApiId *string `json:"api_id,omitempty"`
	Auth *AuthModel `json:"auth,omitempty"`
	AuthProvider *AuthProviderMetaModel `json:"auth_provider,omitempty"`
	BaseIdentityProvidedBy *string `json:"base_identity_provided_by,omitempty"`
	BasicAuth *APIDefinitionBasicAuthModel `json:"basic_auth,omitempty"`
	BlacklistedIps []string `json:"blacklisted_ips,omitempty"`
	CacheOptions *CacheOptionsModel `json:"cache_options,omitempty"`
	Certificates []string `json:"certificates,omitempty"`
	ClientCertificates []string `json:"client_certificates,omitempty"`
	ConfigData map[string]map[string]interface{} `json:"config_data,omitempty"`
	CustomMiddleware *MiddlewareSectionModel `json:"custom_middleware,omitempty"`
	CustomMiddlewareBundle *string `json:"custom_middleware_bundle,omitempty"`
	Definition *APIDefinitionDefinitionModel `json:"definition,omitempty"`
	DisableQuota *bool `json:"disable_quota,omitempty"`
	DisableRateLimit *bool `json:"disable_rate_limit,omitempty"`
	DoNotTrack *bool `json:"do_not_track,omitempty"`
	Domain *string `json:"domain,omitempty"`
	DontSetQuotaOnCreate *bool `json:"dont_set_quota_on_create,omitempty"`
	EnableBatchRequestSupport *bool `json:"enable_batch_request_support,omitempty"`
	EnableContextVars *bool `json:"enable_context_vars,omitempty"`
	EnableCoprocessAuth *bool `json:"enable_coprocess_auth,omitempty"`
	EnableIpBlacklisting *bool `json:"enable_ip_blacklisting,omitempty"`
	EnableIpWhitelisting *bool `json:"enable_ip_whitelisting,omitempty"`
	EnableJwt *bool `json:"enable_jwt,omitempty"`
	EnableSignatureChecking *bool `json:"enable_signature_checking,omitempty"`
	EventHandlers *EventHandlerMetaConfigModel `json:"event_handlers,omitempty"`
	ExpireAnalyticsAfter *int64 `json:"expire_analytics_after,omitempty"`
	GlobalRateLimit *GlobalRateLimitModel `json:"global_rate_limit,omitempty"`
	HmacAllowedAlgorithms []string `json:"hmac_allowed_algorithms,omitempty"`
	HmacAllowedClockSkew *float64 `json:"hmac_allowed_clock_skew,omitempty"`
	// http://www.mongodb.org/display/DOCS/Object+IDs
	Id *string `json:"id,omitempty"`
	Internal *bool `json:"internal,omitempty"`
	JwtClientBaseField *string `json:"jwt_client_base_field,omitempty"`
	JwtExpiresAtValidationSkew *int32 `json:"jwt_expires_at_validation_skew,omitempty"`
	JwtIdentityBaseField *string `json:"jwt_identity_base_field,omitempty"`
	JwtIssuedAtValidationSkew *int32 `json:"jwt_issued_at_validation_skew,omitempty"`
	JwtNotBeforeValidationSkew *int32 `json:"jwt_not_before_validation_skew,omitempty"`
	JwtPolicyFieldName *string `json:"jwt_policy_field_name,omitempty"`
	JwtScopeClaimName *string `json:"jwt_scope_claim_name,omitempty"`
	JwtScopeToPolicyMapping *map[string]string `json:"jwt_scope_to_policy_mapping,omitempty"`
	JwtSigningMethod *string `json:"jwt_signing_method,omitempty"`
	JwtSkipKid *bool `json:"jwt_skip_kid,omitempty"`
	JwtSource *string `json:"jwt_source,omitempty"`
	Name *string `json:"name,omitempty"`
	Notifications *NotificationsManagerModelModel `json:"notifications,omitempty"`
	OauthMeta *APIDefinitionOauthMetaModel `json:"oauth_meta,omitempty"`
	OpenidOptions *OpenIDOptionsModel `json:"openid_options,omitempty"`
	OrgId *string `json:"org_id,omitempty"`
	PinnedPublicKeys *map[string]string `json:"pinned_public_keys,omitempty"`
	Proxy *APIDefinitionProxyModel `json:"proxy,omitempty"`
	ResponseProcessors []ResponseProcessorModel `json:"response_processors,omitempty"`
	SessionLifetime *int64 `json:"session_lifetime,omitempty"`
	SessionProvider *SessionProviderMetaModel `json:"session_provider,omitempty"`
	Slug *string `json:"slug,omitempty"`
	StripAuthData *bool `json:"strip_auth_data,omitempty"`
	TagHeaders []string `json:"tag_headers,omitempty"`
	UpstreamCertificates *map[string]string `json:"upstream_certificates,omitempty"`
	UptimeTests *APIDefinitionUptimeTestsModelModel `json:"uptime_tests,omitempty"`
	UseBasicAuth *bool `json:"use_basic_auth,omitempty"`
	UseKeyless *bool `json:"use_keyless,omitempty"`
	UseMutualTlsAuth *bool `json:"use_mutual_tls_auth,omitempty"`
	UseOauth2 *bool `json:"use_oauth2,omitempty"`
	UseOpenid *bool `json:"use_openid,omitempty"`
	UseStandardAuth *bool `json:"use_standard_auth,omitempty"`
	VersionData *APIDefinitionVersionDataModelModel `json:"version_data,omitempty"`
}

// NewAPIDefinitionModel instantiates a new APIDefinitionModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIDefinitionModel() *APIDefinitionModel {
	this := APIDefinitionModel{}
	return &this
}

// NewAPIDefinitionModelWithDefaults instantiates a new APIDefinitionModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIDefinitionModelWithDefaults() *APIDefinitionModel {
	this := APIDefinitionModel{}
	return &this
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetTagsOk() ([]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *APIDefinitionModel) SetTags(v []string) {
	o.Tags = v
}

// GetCORS returns the CORS field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetCORS() APIDefinitionCORSModel {
	if o == nil || o.CORS == nil {
		var ret APIDefinitionCORSModel
		return ret
	}
	return *o.CORS
}

// GetCORSOk returns a tuple with the CORS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetCORSOk() (*APIDefinitionCORSModel, bool) {
	if o == nil || o.CORS == nil {
		return nil, false
	}
	return o.CORS, true
}

// HasCORS returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasCORS() bool {
	if o != nil && o.CORS != nil {
		return true
	}

	return false
}

// SetCORS gets a reference to the given APIDefinitionCORSModel and assigns it to the CORS field.
func (o *APIDefinitionModel) SetCORS(v APIDefinitionCORSModel) {
	o.CORS = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetActive() bool {
	if o == nil || o.Active == nil {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetActiveOk() (*bool, bool) {
	if o == nil || o.Active == nil {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasActive() bool {
	if o != nil && o.Active != nil {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *APIDefinitionModel) SetActive(v bool) {
	o.Active = &v
}

// GetAllowedIps returns the AllowedIps field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetAllowedIps() []string {
	if o == nil || o.AllowedIps == nil {
		var ret []string
		return ret
	}
	return o.AllowedIps
}

// GetAllowedIpsOk returns a tuple with the AllowedIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetAllowedIpsOk() ([]string, bool) {
	if o == nil || o.AllowedIps == nil {
		return nil, false
	}
	return o.AllowedIps, true
}

// HasAllowedIps returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasAllowedIps() bool {
	if o != nil && o.AllowedIps != nil {
		return true
	}

	return false
}

// SetAllowedIps gets a reference to the given []string and assigns it to the AllowedIps field.
func (o *APIDefinitionModel) SetAllowedIps(v []string) {
	o.AllowedIps = v
}

// GetApiId returns the ApiId field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetApiId() string {
	if o == nil || o.ApiId == nil {
		var ret string
		return ret
	}
	return *o.ApiId
}

// GetApiIdOk returns a tuple with the ApiId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetApiIdOk() (*string, bool) {
	if o == nil || o.ApiId == nil {
		return nil, false
	}
	return o.ApiId, true
}

// HasApiId returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasApiId() bool {
	if o != nil && o.ApiId != nil {
		return true
	}

	return false
}

// SetApiId gets a reference to the given string and assigns it to the ApiId field.
func (o *APIDefinitionModel) SetApiId(v string) {
	o.ApiId = &v
}

// GetAuth returns the Auth field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetAuth() AuthModel {
	if o == nil || o.Auth == nil {
		var ret AuthModel
		return ret
	}
	return *o.Auth
}

// GetAuthOk returns a tuple with the Auth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetAuthOk() (*AuthModel, bool) {
	if o == nil || o.Auth == nil {
		return nil, false
	}
	return o.Auth, true
}

// HasAuth returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasAuth() bool {
	if o != nil && o.Auth != nil {
		return true
	}

	return false
}

// SetAuth gets a reference to the given AuthModel and assigns it to the Auth field.
func (o *APIDefinitionModel) SetAuth(v AuthModel) {
	o.Auth = &v
}

// GetAuthProvider returns the AuthProvider field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetAuthProvider() AuthProviderMetaModel {
	if o == nil || o.AuthProvider == nil {
		var ret AuthProviderMetaModel
		return ret
	}
	return *o.AuthProvider
}

// GetAuthProviderOk returns a tuple with the AuthProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetAuthProviderOk() (*AuthProviderMetaModel, bool) {
	if o == nil || o.AuthProvider == nil {
		return nil, false
	}
	return o.AuthProvider, true
}

// HasAuthProvider returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasAuthProvider() bool {
	if o != nil && o.AuthProvider != nil {
		return true
	}

	return false
}

// SetAuthProvider gets a reference to the given AuthProviderMetaModel and assigns it to the AuthProvider field.
func (o *APIDefinitionModel) SetAuthProvider(v AuthProviderMetaModel) {
	o.AuthProvider = &v
}

// GetBaseIdentityProvidedBy returns the BaseIdentityProvidedBy field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetBaseIdentityProvidedBy() string {
	if o == nil || o.BaseIdentityProvidedBy == nil {
		var ret string
		return ret
	}
	return *o.BaseIdentityProvidedBy
}

// GetBaseIdentityProvidedByOk returns a tuple with the BaseIdentityProvidedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetBaseIdentityProvidedByOk() (*string, bool) {
	if o == nil || o.BaseIdentityProvidedBy == nil {
		return nil, false
	}
	return o.BaseIdentityProvidedBy, true
}

// HasBaseIdentityProvidedBy returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasBaseIdentityProvidedBy() bool {
	if o != nil && o.BaseIdentityProvidedBy != nil {
		return true
	}

	return false
}

// SetBaseIdentityProvidedBy gets a reference to the given string and assigns it to the BaseIdentityProvidedBy field.
func (o *APIDefinitionModel) SetBaseIdentityProvidedBy(v string) {
	o.BaseIdentityProvidedBy = &v
}

// GetBasicAuth returns the BasicAuth field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetBasicAuth() APIDefinitionBasicAuthModel {
	if o == nil || o.BasicAuth == nil {
		var ret APIDefinitionBasicAuthModel
		return ret
	}
	return *o.BasicAuth
}

// GetBasicAuthOk returns a tuple with the BasicAuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetBasicAuthOk() (*APIDefinitionBasicAuthModel, bool) {
	if o == nil || o.BasicAuth == nil {
		return nil, false
	}
	return o.BasicAuth, true
}

// HasBasicAuth returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasBasicAuth() bool {
	if o != nil && o.BasicAuth != nil {
		return true
	}

	return false
}

// SetBasicAuth gets a reference to the given APIDefinitionBasicAuthModel and assigns it to the BasicAuth field.
func (o *APIDefinitionModel) SetBasicAuth(v APIDefinitionBasicAuthModel) {
	o.BasicAuth = &v
}

// GetBlacklistedIps returns the BlacklistedIps field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetBlacklistedIps() []string {
	if o == nil || o.BlacklistedIps == nil {
		var ret []string
		return ret
	}
	return o.BlacklistedIps
}

// GetBlacklistedIpsOk returns a tuple with the BlacklistedIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetBlacklistedIpsOk() ([]string, bool) {
	if o == nil || o.BlacklistedIps == nil {
		return nil, false
	}
	return o.BlacklistedIps, true
}

// HasBlacklistedIps returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasBlacklistedIps() bool {
	if o != nil && o.BlacklistedIps != nil {
		return true
	}

	return false
}

// SetBlacklistedIps gets a reference to the given []string and assigns it to the BlacklistedIps field.
func (o *APIDefinitionModel) SetBlacklistedIps(v []string) {
	o.BlacklistedIps = v
}

// GetCacheOptions returns the CacheOptions field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetCacheOptions() CacheOptionsModel {
	if o == nil || o.CacheOptions == nil {
		var ret CacheOptionsModel
		return ret
	}
	return *o.CacheOptions
}

// GetCacheOptionsOk returns a tuple with the CacheOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetCacheOptionsOk() (*CacheOptionsModel, bool) {
	if o == nil || o.CacheOptions == nil {
		return nil, false
	}
	return o.CacheOptions, true
}

// HasCacheOptions returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasCacheOptions() bool {
	if o != nil && o.CacheOptions != nil {
		return true
	}

	return false
}

// SetCacheOptions gets a reference to the given CacheOptionsModel and assigns it to the CacheOptions field.
func (o *APIDefinitionModel) SetCacheOptions(v CacheOptionsModel) {
	o.CacheOptions = &v
}

// GetCertificates returns the Certificates field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetCertificates() []string {
	if o == nil || o.Certificates == nil {
		var ret []string
		return ret
	}
	return o.Certificates
}

// GetCertificatesOk returns a tuple with the Certificates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetCertificatesOk() ([]string, bool) {
	if o == nil || o.Certificates == nil {
		return nil, false
	}
	return o.Certificates, true
}

// HasCertificates returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasCertificates() bool {
	if o != nil && o.Certificates != nil {
		return true
	}

	return false
}

// SetCertificates gets a reference to the given []string and assigns it to the Certificates field.
func (o *APIDefinitionModel) SetCertificates(v []string) {
	o.Certificates = v
}

// GetClientCertificates returns the ClientCertificates field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetClientCertificates() []string {
	if o == nil || o.ClientCertificates == nil {
		var ret []string
		return ret
	}
	return o.ClientCertificates
}

// GetClientCertificatesOk returns a tuple with the ClientCertificates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetClientCertificatesOk() ([]string, bool) {
	if o == nil || o.ClientCertificates == nil {
		return nil, false
	}
	return o.ClientCertificates, true
}

// HasClientCertificates returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasClientCertificates() bool {
	if o != nil && o.ClientCertificates != nil {
		return true
	}

	return false
}

// SetClientCertificates gets a reference to the given []string and assigns it to the ClientCertificates field.
func (o *APIDefinitionModel) SetClientCertificates(v []string) {
	o.ClientCertificates = v
}

// GetConfigData returns the ConfigData field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetConfigData() map[string]map[string]interface{} {
	if o == nil || o.ConfigData == nil {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.ConfigData
}

// GetConfigDataOk returns a tuple with the ConfigData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetConfigDataOk() (map[string]map[string]interface{}, bool) {
	if o == nil || o.ConfigData == nil {
		return nil, false
	}
	return o.ConfigData, true
}

// HasConfigData returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasConfigData() bool {
	if o != nil && o.ConfigData != nil {
		return true
	}

	return false
}

// SetConfigData gets a reference to the given map[string]map[string]interface{} and assigns it to the ConfigData field.
func (o *APIDefinitionModel) SetConfigData(v map[string]map[string]interface{}) {
	o.ConfigData = v
}

// GetCustomMiddleware returns the CustomMiddleware field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetCustomMiddleware() MiddlewareSectionModel {
	if o == nil || o.CustomMiddleware == nil {
		var ret MiddlewareSectionModel
		return ret
	}
	return *o.CustomMiddleware
}

// GetCustomMiddlewareOk returns a tuple with the CustomMiddleware field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetCustomMiddlewareOk() (*MiddlewareSectionModel, bool) {
	if o == nil || o.CustomMiddleware == nil {
		return nil, false
	}
	return o.CustomMiddleware, true
}

// HasCustomMiddleware returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasCustomMiddleware() bool {
	if o != nil && o.CustomMiddleware != nil {
		return true
	}

	return false
}

// SetCustomMiddleware gets a reference to the given MiddlewareSectionModel and assigns it to the CustomMiddleware field.
func (o *APIDefinitionModel) SetCustomMiddleware(v MiddlewareSectionModel) {
	o.CustomMiddleware = &v
}

// GetCustomMiddlewareBundle returns the CustomMiddlewareBundle field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetCustomMiddlewareBundle() string {
	if o == nil || o.CustomMiddlewareBundle == nil {
		var ret string
		return ret
	}
	return *o.CustomMiddlewareBundle
}

// GetCustomMiddlewareBundleOk returns a tuple with the CustomMiddlewareBundle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetCustomMiddlewareBundleOk() (*string, bool) {
	if o == nil || o.CustomMiddlewareBundle == nil {
		return nil, false
	}
	return o.CustomMiddlewareBundle, true
}

// HasCustomMiddlewareBundle returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasCustomMiddlewareBundle() bool {
	if o != nil && o.CustomMiddlewareBundle != nil {
		return true
	}

	return false
}

// SetCustomMiddlewareBundle gets a reference to the given string and assigns it to the CustomMiddlewareBundle field.
func (o *APIDefinitionModel) SetCustomMiddlewareBundle(v string) {
	o.CustomMiddlewareBundle = &v
}

// GetDefinition returns the Definition field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetDefinition() APIDefinitionDefinitionModel {
	if o == nil || o.Definition == nil {
		var ret APIDefinitionDefinitionModel
		return ret
	}
	return *o.Definition
}

// GetDefinitionOk returns a tuple with the Definition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetDefinitionOk() (*APIDefinitionDefinitionModel, bool) {
	if o == nil || o.Definition == nil {
		return nil, false
	}
	return o.Definition, true
}

// HasDefinition returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasDefinition() bool {
	if o != nil && o.Definition != nil {
		return true
	}

	return false
}

// SetDefinition gets a reference to the given APIDefinitionDefinitionModel and assigns it to the Definition field.
func (o *APIDefinitionModel) SetDefinition(v APIDefinitionDefinitionModel) {
	o.Definition = &v
}

// GetDisableQuota returns the DisableQuota field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetDisableQuota() bool {
	if o == nil || o.DisableQuota == nil {
		var ret bool
		return ret
	}
	return *o.DisableQuota
}

// GetDisableQuotaOk returns a tuple with the DisableQuota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetDisableQuotaOk() (*bool, bool) {
	if o == nil || o.DisableQuota == nil {
		return nil, false
	}
	return o.DisableQuota, true
}

// HasDisableQuota returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasDisableQuota() bool {
	if o != nil && o.DisableQuota != nil {
		return true
	}

	return false
}

// SetDisableQuota gets a reference to the given bool and assigns it to the DisableQuota field.
func (o *APIDefinitionModel) SetDisableQuota(v bool) {
	o.DisableQuota = &v
}

// GetDisableRateLimit returns the DisableRateLimit field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetDisableRateLimit() bool {
	if o == nil || o.DisableRateLimit == nil {
		var ret bool
		return ret
	}
	return *o.DisableRateLimit
}

// GetDisableRateLimitOk returns a tuple with the DisableRateLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetDisableRateLimitOk() (*bool, bool) {
	if o == nil || o.DisableRateLimit == nil {
		return nil, false
	}
	return o.DisableRateLimit, true
}

// HasDisableRateLimit returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasDisableRateLimit() bool {
	if o != nil && o.DisableRateLimit != nil {
		return true
	}

	return false
}

// SetDisableRateLimit gets a reference to the given bool and assigns it to the DisableRateLimit field.
func (o *APIDefinitionModel) SetDisableRateLimit(v bool) {
	o.DisableRateLimit = &v
}

// GetDoNotTrack returns the DoNotTrack field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetDoNotTrack() bool {
	if o == nil || o.DoNotTrack == nil {
		var ret bool
		return ret
	}
	return *o.DoNotTrack
}

// GetDoNotTrackOk returns a tuple with the DoNotTrack field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetDoNotTrackOk() (*bool, bool) {
	if o == nil || o.DoNotTrack == nil {
		return nil, false
	}
	return o.DoNotTrack, true
}

// HasDoNotTrack returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasDoNotTrack() bool {
	if o != nil && o.DoNotTrack != nil {
		return true
	}

	return false
}

// SetDoNotTrack gets a reference to the given bool and assigns it to the DoNotTrack field.
func (o *APIDefinitionModel) SetDoNotTrack(v bool) {
	o.DoNotTrack = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetDomain() string {
	if o == nil || o.Domain == nil {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetDomainOk() (*string, bool) {
	if o == nil || o.Domain == nil {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasDomain() bool {
	if o != nil && o.Domain != nil {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *APIDefinitionModel) SetDomain(v string) {
	o.Domain = &v
}

// GetDontSetQuotaOnCreate returns the DontSetQuotaOnCreate field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetDontSetQuotaOnCreate() bool {
	if o == nil || o.DontSetQuotaOnCreate == nil {
		var ret bool
		return ret
	}
	return *o.DontSetQuotaOnCreate
}

// GetDontSetQuotaOnCreateOk returns a tuple with the DontSetQuotaOnCreate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetDontSetQuotaOnCreateOk() (*bool, bool) {
	if o == nil || o.DontSetQuotaOnCreate == nil {
		return nil, false
	}
	return o.DontSetQuotaOnCreate, true
}

// HasDontSetQuotaOnCreate returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasDontSetQuotaOnCreate() bool {
	if o != nil && o.DontSetQuotaOnCreate != nil {
		return true
	}

	return false
}

// SetDontSetQuotaOnCreate gets a reference to the given bool and assigns it to the DontSetQuotaOnCreate field.
func (o *APIDefinitionModel) SetDontSetQuotaOnCreate(v bool) {
	o.DontSetQuotaOnCreate = &v
}

// GetEnableBatchRequestSupport returns the EnableBatchRequestSupport field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetEnableBatchRequestSupport() bool {
	if o == nil || o.EnableBatchRequestSupport == nil {
		var ret bool
		return ret
	}
	return *o.EnableBatchRequestSupport
}

// GetEnableBatchRequestSupportOk returns a tuple with the EnableBatchRequestSupport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetEnableBatchRequestSupportOk() (*bool, bool) {
	if o == nil || o.EnableBatchRequestSupport == nil {
		return nil, false
	}
	return o.EnableBatchRequestSupport, true
}

// HasEnableBatchRequestSupport returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasEnableBatchRequestSupport() bool {
	if o != nil && o.EnableBatchRequestSupport != nil {
		return true
	}

	return false
}

// SetEnableBatchRequestSupport gets a reference to the given bool and assigns it to the EnableBatchRequestSupport field.
func (o *APIDefinitionModel) SetEnableBatchRequestSupport(v bool) {
	o.EnableBatchRequestSupport = &v
}

// GetEnableContextVars returns the EnableContextVars field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetEnableContextVars() bool {
	if o == nil || o.EnableContextVars == nil {
		var ret bool
		return ret
	}
	return *o.EnableContextVars
}

// GetEnableContextVarsOk returns a tuple with the EnableContextVars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetEnableContextVarsOk() (*bool, bool) {
	if o == nil || o.EnableContextVars == nil {
		return nil, false
	}
	return o.EnableContextVars, true
}

// HasEnableContextVars returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasEnableContextVars() bool {
	if o != nil && o.EnableContextVars != nil {
		return true
	}

	return false
}

// SetEnableContextVars gets a reference to the given bool and assigns it to the EnableContextVars field.
func (o *APIDefinitionModel) SetEnableContextVars(v bool) {
	o.EnableContextVars = &v
}

// GetEnableCoprocessAuth returns the EnableCoprocessAuth field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetEnableCoprocessAuth() bool {
	if o == nil || o.EnableCoprocessAuth == nil {
		var ret bool
		return ret
	}
	return *o.EnableCoprocessAuth
}

// GetEnableCoprocessAuthOk returns a tuple with the EnableCoprocessAuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetEnableCoprocessAuthOk() (*bool, bool) {
	if o == nil || o.EnableCoprocessAuth == nil {
		return nil, false
	}
	return o.EnableCoprocessAuth, true
}

// HasEnableCoprocessAuth returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasEnableCoprocessAuth() bool {
	if o != nil && o.EnableCoprocessAuth != nil {
		return true
	}

	return false
}

// SetEnableCoprocessAuth gets a reference to the given bool and assigns it to the EnableCoprocessAuth field.
func (o *APIDefinitionModel) SetEnableCoprocessAuth(v bool) {
	o.EnableCoprocessAuth = &v
}

// GetEnableIpBlacklisting returns the EnableIpBlacklisting field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetEnableIpBlacklisting() bool {
	if o == nil || o.EnableIpBlacklisting == nil {
		var ret bool
		return ret
	}
	return *o.EnableIpBlacklisting
}

// GetEnableIpBlacklistingOk returns a tuple with the EnableIpBlacklisting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetEnableIpBlacklistingOk() (*bool, bool) {
	if o == nil || o.EnableIpBlacklisting == nil {
		return nil, false
	}
	return o.EnableIpBlacklisting, true
}

// HasEnableIpBlacklisting returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasEnableIpBlacklisting() bool {
	if o != nil && o.EnableIpBlacklisting != nil {
		return true
	}

	return false
}

// SetEnableIpBlacklisting gets a reference to the given bool and assigns it to the EnableIpBlacklisting field.
func (o *APIDefinitionModel) SetEnableIpBlacklisting(v bool) {
	o.EnableIpBlacklisting = &v
}

// GetEnableIpWhitelisting returns the EnableIpWhitelisting field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetEnableIpWhitelisting() bool {
	if o == nil || o.EnableIpWhitelisting == nil {
		var ret bool
		return ret
	}
	return *o.EnableIpWhitelisting
}

// GetEnableIpWhitelistingOk returns a tuple with the EnableIpWhitelisting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetEnableIpWhitelistingOk() (*bool, bool) {
	if o == nil || o.EnableIpWhitelisting == nil {
		return nil, false
	}
	return o.EnableIpWhitelisting, true
}

// HasEnableIpWhitelisting returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasEnableIpWhitelisting() bool {
	if o != nil && o.EnableIpWhitelisting != nil {
		return true
	}

	return false
}

// SetEnableIpWhitelisting gets a reference to the given bool and assigns it to the EnableIpWhitelisting field.
func (o *APIDefinitionModel) SetEnableIpWhitelisting(v bool) {
	o.EnableIpWhitelisting = &v
}

// GetEnableJwt returns the EnableJwt field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetEnableJwt() bool {
	if o == nil || o.EnableJwt == nil {
		var ret bool
		return ret
	}
	return *o.EnableJwt
}

// GetEnableJwtOk returns a tuple with the EnableJwt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetEnableJwtOk() (*bool, bool) {
	if o == nil || o.EnableJwt == nil {
		return nil, false
	}
	return o.EnableJwt, true
}

// HasEnableJwt returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasEnableJwt() bool {
	if o != nil && o.EnableJwt != nil {
		return true
	}

	return false
}

// SetEnableJwt gets a reference to the given bool and assigns it to the EnableJwt field.
func (o *APIDefinitionModel) SetEnableJwt(v bool) {
	o.EnableJwt = &v
}

// GetEnableSignatureChecking returns the EnableSignatureChecking field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetEnableSignatureChecking() bool {
	if o == nil || o.EnableSignatureChecking == nil {
		var ret bool
		return ret
	}
	return *o.EnableSignatureChecking
}

// GetEnableSignatureCheckingOk returns a tuple with the EnableSignatureChecking field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetEnableSignatureCheckingOk() (*bool, bool) {
	if o == nil || o.EnableSignatureChecking == nil {
		return nil, false
	}
	return o.EnableSignatureChecking, true
}

// HasEnableSignatureChecking returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasEnableSignatureChecking() bool {
	if o != nil && o.EnableSignatureChecking != nil {
		return true
	}

	return false
}

// SetEnableSignatureChecking gets a reference to the given bool and assigns it to the EnableSignatureChecking field.
func (o *APIDefinitionModel) SetEnableSignatureChecking(v bool) {
	o.EnableSignatureChecking = &v
}

// GetEventHandlers returns the EventHandlers field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetEventHandlers() EventHandlerMetaConfigModel {
	if o == nil || o.EventHandlers == nil {
		var ret EventHandlerMetaConfigModel
		return ret
	}
	return *o.EventHandlers
}

// GetEventHandlersOk returns a tuple with the EventHandlers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetEventHandlersOk() (*EventHandlerMetaConfigModel, bool) {
	if o == nil || o.EventHandlers == nil {
		return nil, false
	}
	return o.EventHandlers, true
}

// HasEventHandlers returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasEventHandlers() bool {
	if o != nil && o.EventHandlers != nil {
		return true
	}

	return false
}

// SetEventHandlers gets a reference to the given EventHandlerMetaConfigModel and assigns it to the EventHandlers field.
func (o *APIDefinitionModel) SetEventHandlers(v EventHandlerMetaConfigModel) {
	o.EventHandlers = &v
}

// GetExpireAnalyticsAfter returns the ExpireAnalyticsAfter field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetExpireAnalyticsAfter() int64 {
	if o == nil || o.ExpireAnalyticsAfter == nil {
		var ret int64
		return ret
	}
	return *o.ExpireAnalyticsAfter
}

// GetExpireAnalyticsAfterOk returns a tuple with the ExpireAnalyticsAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetExpireAnalyticsAfterOk() (*int64, bool) {
	if o == nil || o.ExpireAnalyticsAfter == nil {
		return nil, false
	}
	return o.ExpireAnalyticsAfter, true
}

// HasExpireAnalyticsAfter returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasExpireAnalyticsAfter() bool {
	if o != nil && o.ExpireAnalyticsAfter != nil {
		return true
	}

	return false
}

// SetExpireAnalyticsAfter gets a reference to the given int64 and assigns it to the ExpireAnalyticsAfter field.
func (o *APIDefinitionModel) SetExpireAnalyticsAfter(v int64) {
	o.ExpireAnalyticsAfter = &v
}

// GetGlobalRateLimit returns the GlobalRateLimit field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetGlobalRateLimit() GlobalRateLimitModel {
	if o == nil || o.GlobalRateLimit == nil {
		var ret GlobalRateLimitModel
		return ret
	}
	return *o.GlobalRateLimit
}

// GetGlobalRateLimitOk returns a tuple with the GlobalRateLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetGlobalRateLimitOk() (*GlobalRateLimitModel, bool) {
	if o == nil || o.GlobalRateLimit == nil {
		return nil, false
	}
	return o.GlobalRateLimit, true
}

// HasGlobalRateLimit returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasGlobalRateLimit() bool {
	if o != nil && o.GlobalRateLimit != nil {
		return true
	}

	return false
}

// SetGlobalRateLimit gets a reference to the given GlobalRateLimitModel and assigns it to the GlobalRateLimit field.
func (o *APIDefinitionModel) SetGlobalRateLimit(v GlobalRateLimitModel) {
	o.GlobalRateLimit = &v
}

// GetHmacAllowedAlgorithms returns the HmacAllowedAlgorithms field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetHmacAllowedAlgorithms() []string {
	if o == nil || o.HmacAllowedAlgorithms == nil {
		var ret []string
		return ret
	}
	return o.HmacAllowedAlgorithms
}

// GetHmacAllowedAlgorithmsOk returns a tuple with the HmacAllowedAlgorithms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetHmacAllowedAlgorithmsOk() ([]string, bool) {
	if o == nil || o.HmacAllowedAlgorithms == nil {
		return nil, false
	}
	return o.HmacAllowedAlgorithms, true
}

// HasHmacAllowedAlgorithms returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasHmacAllowedAlgorithms() bool {
	if o != nil && o.HmacAllowedAlgorithms != nil {
		return true
	}

	return false
}

// SetHmacAllowedAlgorithms gets a reference to the given []string and assigns it to the HmacAllowedAlgorithms field.
func (o *APIDefinitionModel) SetHmacAllowedAlgorithms(v []string) {
	o.HmacAllowedAlgorithms = v
}

// GetHmacAllowedClockSkew returns the HmacAllowedClockSkew field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetHmacAllowedClockSkew() float64 {
	if o == nil || o.HmacAllowedClockSkew == nil {
		var ret float64
		return ret
	}
	return *o.HmacAllowedClockSkew
}

// GetHmacAllowedClockSkewOk returns a tuple with the HmacAllowedClockSkew field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetHmacAllowedClockSkewOk() (*float64, bool) {
	if o == nil || o.HmacAllowedClockSkew == nil {
		return nil, false
	}
	return o.HmacAllowedClockSkew, true
}

// HasHmacAllowedClockSkew returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasHmacAllowedClockSkew() bool {
	if o != nil && o.HmacAllowedClockSkew != nil {
		return true
	}

	return false
}

// SetHmacAllowedClockSkew gets a reference to the given float64 and assigns it to the HmacAllowedClockSkew field.
func (o *APIDefinitionModel) SetHmacAllowedClockSkew(v float64) {
	o.HmacAllowedClockSkew = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *APIDefinitionModel) SetId(v string) {
	o.Id = &v
}

// GetInternal returns the Internal field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetInternal() bool {
	if o == nil || o.Internal == nil {
		var ret bool
		return ret
	}
	return *o.Internal
}

// GetInternalOk returns a tuple with the Internal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetInternalOk() (*bool, bool) {
	if o == nil || o.Internal == nil {
		return nil, false
	}
	return o.Internal, true
}

// HasInternal returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasInternal() bool {
	if o != nil && o.Internal != nil {
		return true
	}

	return false
}

// SetInternal gets a reference to the given bool and assigns it to the Internal field.
func (o *APIDefinitionModel) SetInternal(v bool) {
	o.Internal = &v
}

// GetJwtClientBaseField returns the JwtClientBaseField field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetJwtClientBaseField() string {
	if o == nil || o.JwtClientBaseField == nil {
		var ret string
		return ret
	}
	return *o.JwtClientBaseField
}

// GetJwtClientBaseFieldOk returns a tuple with the JwtClientBaseField field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetJwtClientBaseFieldOk() (*string, bool) {
	if o == nil || o.JwtClientBaseField == nil {
		return nil, false
	}
	return o.JwtClientBaseField, true
}

// HasJwtClientBaseField returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasJwtClientBaseField() bool {
	if o != nil && o.JwtClientBaseField != nil {
		return true
	}

	return false
}

// SetJwtClientBaseField gets a reference to the given string and assigns it to the JwtClientBaseField field.
func (o *APIDefinitionModel) SetJwtClientBaseField(v string) {
	o.JwtClientBaseField = &v
}

// GetJwtExpiresAtValidationSkew returns the JwtExpiresAtValidationSkew field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetJwtExpiresAtValidationSkew() int32 {
	if o == nil || o.JwtExpiresAtValidationSkew == nil {
		var ret int32
		return ret
	}
	return *o.JwtExpiresAtValidationSkew
}

// GetJwtExpiresAtValidationSkewOk returns a tuple with the JwtExpiresAtValidationSkew field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetJwtExpiresAtValidationSkewOk() (*int32, bool) {
	if o == nil || o.JwtExpiresAtValidationSkew == nil {
		return nil, false
	}
	return o.JwtExpiresAtValidationSkew, true
}

// HasJwtExpiresAtValidationSkew returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasJwtExpiresAtValidationSkew() bool {
	if o != nil && o.JwtExpiresAtValidationSkew != nil {
		return true
	}

	return false
}

// SetJwtExpiresAtValidationSkew gets a reference to the given int32 and assigns it to the JwtExpiresAtValidationSkew field.
func (o *APIDefinitionModel) SetJwtExpiresAtValidationSkew(v int32) {
	o.JwtExpiresAtValidationSkew = &v
}

// GetJwtIdentityBaseField returns the JwtIdentityBaseField field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetJwtIdentityBaseField() string {
	if o == nil || o.JwtIdentityBaseField == nil {
		var ret string
		return ret
	}
	return *o.JwtIdentityBaseField
}

// GetJwtIdentityBaseFieldOk returns a tuple with the JwtIdentityBaseField field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetJwtIdentityBaseFieldOk() (*string, bool) {
	if o == nil || o.JwtIdentityBaseField == nil {
		return nil, false
	}
	return o.JwtIdentityBaseField, true
}

// HasJwtIdentityBaseField returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasJwtIdentityBaseField() bool {
	if o != nil && o.JwtIdentityBaseField != nil {
		return true
	}

	return false
}

// SetJwtIdentityBaseField gets a reference to the given string and assigns it to the JwtIdentityBaseField field.
func (o *APIDefinitionModel) SetJwtIdentityBaseField(v string) {
	o.JwtIdentityBaseField = &v
}

// GetJwtIssuedAtValidationSkew returns the JwtIssuedAtValidationSkew field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetJwtIssuedAtValidationSkew() int32 {
	if o == nil || o.JwtIssuedAtValidationSkew == nil {
		var ret int32
		return ret
	}
	return *o.JwtIssuedAtValidationSkew
}

// GetJwtIssuedAtValidationSkewOk returns a tuple with the JwtIssuedAtValidationSkew field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetJwtIssuedAtValidationSkewOk() (*int32, bool) {
	if o == nil || o.JwtIssuedAtValidationSkew == nil {
		return nil, false
	}
	return o.JwtIssuedAtValidationSkew, true
}

// HasJwtIssuedAtValidationSkew returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasJwtIssuedAtValidationSkew() bool {
	if o != nil && o.JwtIssuedAtValidationSkew != nil {
		return true
	}

	return false
}

// SetJwtIssuedAtValidationSkew gets a reference to the given int32 and assigns it to the JwtIssuedAtValidationSkew field.
func (o *APIDefinitionModel) SetJwtIssuedAtValidationSkew(v int32) {
	o.JwtIssuedAtValidationSkew = &v
}

// GetJwtNotBeforeValidationSkew returns the JwtNotBeforeValidationSkew field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetJwtNotBeforeValidationSkew() int32 {
	if o == nil || o.JwtNotBeforeValidationSkew == nil {
		var ret int32
		return ret
	}
	return *o.JwtNotBeforeValidationSkew
}

// GetJwtNotBeforeValidationSkewOk returns a tuple with the JwtNotBeforeValidationSkew field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetJwtNotBeforeValidationSkewOk() (*int32, bool) {
	if o == nil || o.JwtNotBeforeValidationSkew == nil {
		return nil, false
	}
	return o.JwtNotBeforeValidationSkew, true
}

// HasJwtNotBeforeValidationSkew returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasJwtNotBeforeValidationSkew() bool {
	if o != nil && o.JwtNotBeforeValidationSkew != nil {
		return true
	}

	return false
}

// SetJwtNotBeforeValidationSkew gets a reference to the given int32 and assigns it to the JwtNotBeforeValidationSkew field.
func (o *APIDefinitionModel) SetJwtNotBeforeValidationSkew(v int32) {
	o.JwtNotBeforeValidationSkew = &v
}

// GetJwtPolicyFieldName returns the JwtPolicyFieldName field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetJwtPolicyFieldName() string {
	if o == nil || o.JwtPolicyFieldName == nil {
		var ret string
		return ret
	}
	return *o.JwtPolicyFieldName
}

// GetJwtPolicyFieldNameOk returns a tuple with the JwtPolicyFieldName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetJwtPolicyFieldNameOk() (*string, bool) {
	if o == nil || o.JwtPolicyFieldName == nil {
		return nil, false
	}
	return o.JwtPolicyFieldName, true
}

// HasJwtPolicyFieldName returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasJwtPolicyFieldName() bool {
	if o != nil && o.JwtPolicyFieldName != nil {
		return true
	}

	return false
}

// SetJwtPolicyFieldName gets a reference to the given string and assigns it to the JwtPolicyFieldName field.
func (o *APIDefinitionModel) SetJwtPolicyFieldName(v string) {
	o.JwtPolicyFieldName = &v
}

// GetJwtScopeClaimName returns the JwtScopeClaimName field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetJwtScopeClaimName() string {
	if o == nil || o.JwtScopeClaimName == nil {
		var ret string
		return ret
	}
	return *o.JwtScopeClaimName
}

// GetJwtScopeClaimNameOk returns a tuple with the JwtScopeClaimName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetJwtScopeClaimNameOk() (*string, bool) {
	if o == nil || o.JwtScopeClaimName == nil {
		return nil, false
	}
	return o.JwtScopeClaimName, true
}

// HasJwtScopeClaimName returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasJwtScopeClaimName() bool {
	if o != nil && o.JwtScopeClaimName != nil {
		return true
	}

	return false
}

// SetJwtScopeClaimName gets a reference to the given string and assigns it to the JwtScopeClaimName field.
func (o *APIDefinitionModel) SetJwtScopeClaimName(v string) {
	o.JwtScopeClaimName = &v
}

// GetJwtScopeToPolicyMapping returns the JwtScopeToPolicyMapping field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetJwtScopeToPolicyMapping() map[string]string {
	if o == nil || o.JwtScopeToPolicyMapping == nil {
		var ret map[string]string
		return ret
	}
	return *o.JwtScopeToPolicyMapping
}

// GetJwtScopeToPolicyMappingOk returns a tuple with the JwtScopeToPolicyMapping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetJwtScopeToPolicyMappingOk() (*map[string]string, bool) {
	if o == nil || o.JwtScopeToPolicyMapping == nil {
		return nil, false
	}
	return o.JwtScopeToPolicyMapping, true
}

// HasJwtScopeToPolicyMapping returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasJwtScopeToPolicyMapping() bool {
	if o != nil && o.JwtScopeToPolicyMapping != nil {
		return true
	}

	return false
}

// SetJwtScopeToPolicyMapping gets a reference to the given map[string]string and assigns it to the JwtScopeToPolicyMapping field.
func (o *APIDefinitionModel) SetJwtScopeToPolicyMapping(v map[string]string) {
	o.JwtScopeToPolicyMapping = &v
}

// GetJwtSigningMethod returns the JwtSigningMethod field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetJwtSigningMethod() string {
	if o == nil || o.JwtSigningMethod == nil {
		var ret string
		return ret
	}
	return *o.JwtSigningMethod
}

// GetJwtSigningMethodOk returns a tuple with the JwtSigningMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetJwtSigningMethodOk() (*string, bool) {
	if o == nil || o.JwtSigningMethod == nil {
		return nil, false
	}
	return o.JwtSigningMethod, true
}

// HasJwtSigningMethod returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasJwtSigningMethod() bool {
	if o != nil && o.JwtSigningMethod != nil {
		return true
	}

	return false
}

// SetJwtSigningMethod gets a reference to the given string and assigns it to the JwtSigningMethod field.
func (o *APIDefinitionModel) SetJwtSigningMethod(v string) {
	o.JwtSigningMethod = &v
}

// GetJwtSkipKid returns the JwtSkipKid field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetJwtSkipKid() bool {
	if o == nil || o.JwtSkipKid == nil {
		var ret bool
		return ret
	}
	return *o.JwtSkipKid
}

// GetJwtSkipKidOk returns a tuple with the JwtSkipKid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetJwtSkipKidOk() (*bool, bool) {
	if o == nil || o.JwtSkipKid == nil {
		return nil, false
	}
	return o.JwtSkipKid, true
}

// HasJwtSkipKid returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasJwtSkipKid() bool {
	if o != nil && o.JwtSkipKid != nil {
		return true
	}

	return false
}

// SetJwtSkipKid gets a reference to the given bool and assigns it to the JwtSkipKid field.
func (o *APIDefinitionModel) SetJwtSkipKid(v bool) {
	o.JwtSkipKid = &v
}

// GetJwtSource returns the JwtSource field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetJwtSource() string {
	if o == nil || o.JwtSource == nil {
		var ret string
		return ret
	}
	return *o.JwtSource
}

// GetJwtSourceOk returns a tuple with the JwtSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetJwtSourceOk() (*string, bool) {
	if o == nil || o.JwtSource == nil {
		return nil, false
	}
	return o.JwtSource, true
}

// HasJwtSource returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasJwtSource() bool {
	if o != nil && o.JwtSource != nil {
		return true
	}

	return false
}

// SetJwtSource gets a reference to the given string and assigns it to the JwtSource field.
func (o *APIDefinitionModel) SetJwtSource(v string) {
	o.JwtSource = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *APIDefinitionModel) SetName(v string) {
	o.Name = &v
}

// GetNotifications returns the Notifications field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetNotifications() NotificationsManagerModelModel {
	if o == nil || o.Notifications == nil {
		var ret NotificationsManagerModelModel
		return ret
	}
	return *o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetNotificationsOk() (*NotificationsManagerModelModel, bool) {
	if o == nil || o.Notifications == nil {
		return nil, false
	}
	return o.Notifications, true
}

// HasNotifications returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasNotifications() bool {
	if o != nil && o.Notifications != nil {
		return true
	}

	return false
}

// SetNotifications gets a reference to the given NotificationsManagerModelModel and assigns it to the Notifications field.
func (o *APIDefinitionModel) SetNotifications(v NotificationsManagerModelModel) {
	o.Notifications = &v
}

// GetOauthMeta returns the OauthMeta field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetOauthMeta() APIDefinitionOauthMetaModel {
	if o == nil || o.OauthMeta == nil {
		var ret APIDefinitionOauthMetaModel
		return ret
	}
	return *o.OauthMeta
}

// GetOauthMetaOk returns a tuple with the OauthMeta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetOauthMetaOk() (*APIDefinitionOauthMetaModel, bool) {
	if o == nil || o.OauthMeta == nil {
		return nil, false
	}
	return o.OauthMeta, true
}

// HasOauthMeta returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasOauthMeta() bool {
	if o != nil && o.OauthMeta != nil {
		return true
	}

	return false
}

// SetOauthMeta gets a reference to the given APIDefinitionOauthMetaModel and assigns it to the OauthMeta field.
func (o *APIDefinitionModel) SetOauthMeta(v APIDefinitionOauthMetaModel) {
	o.OauthMeta = &v
}

// GetOpenidOptions returns the OpenidOptions field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetOpenidOptions() OpenIDOptionsModel {
	if o == nil || o.OpenidOptions == nil {
		var ret OpenIDOptionsModel
		return ret
	}
	return *o.OpenidOptions
}

// GetOpenidOptionsOk returns a tuple with the OpenidOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetOpenidOptionsOk() (*OpenIDOptionsModel, bool) {
	if o == nil || o.OpenidOptions == nil {
		return nil, false
	}
	return o.OpenidOptions, true
}

// HasOpenidOptions returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasOpenidOptions() bool {
	if o != nil && o.OpenidOptions != nil {
		return true
	}

	return false
}

// SetOpenidOptions gets a reference to the given OpenIDOptionsModel and assigns it to the OpenidOptions field.
func (o *APIDefinitionModel) SetOpenidOptions(v OpenIDOptionsModel) {
	o.OpenidOptions = &v
}

// GetOrgId returns the OrgId field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetOrgId() string {
	if o == nil || o.OrgId == nil {
		var ret string
		return ret
	}
	return *o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetOrgIdOk() (*string, bool) {
	if o == nil || o.OrgId == nil {
		return nil, false
	}
	return o.OrgId, true
}

// HasOrgId returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasOrgId() bool {
	if o != nil && o.OrgId != nil {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given string and assigns it to the OrgId field.
func (o *APIDefinitionModel) SetOrgId(v string) {
	o.OrgId = &v
}

// GetPinnedPublicKeys returns the PinnedPublicKeys field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetPinnedPublicKeys() map[string]string {
	if o == nil || o.PinnedPublicKeys == nil {
		var ret map[string]string
		return ret
	}
	return *o.PinnedPublicKeys
}

// GetPinnedPublicKeysOk returns a tuple with the PinnedPublicKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetPinnedPublicKeysOk() (*map[string]string, bool) {
	if o == nil || o.PinnedPublicKeys == nil {
		return nil, false
	}
	return o.PinnedPublicKeys, true
}

// HasPinnedPublicKeys returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasPinnedPublicKeys() bool {
	if o != nil && o.PinnedPublicKeys != nil {
		return true
	}

	return false
}

// SetPinnedPublicKeys gets a reference to the given map[string]string and assigns it to the PinnedPublicKeys field.
func (o *APIDefinitionModel) SetPinnedPublicKeys(v map[string]string) {
	o.PinnedPublicKeys = &v
}

// GetProxy returns the Proxy field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetProxy() APIDefinitionProxyModel {
	if o == nil || o.Proxy == nil {
		var ret APIDefinitionProxyModel
		return ret
	}
	return *o.Proxy
}

// GetProxyOk returns a tuple with the Proxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetProxyOk() (*APIDefinitionProxyModel, bool) {
	if o == nil || o.Proxy == nil {
		return nil, false
	}
	return o.Proxy, true
}

// HasProxy returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasProxy() bool {
	if o != nil && o.Proxy != nil {
		return true
	}

	return false
}

// SetProxy gets a reference to the given APIDefinitionProxyModel and assigns it to the Proxy field.
func (o *APIDefinitionModel) SetProxy(v APIDefinitionProxyModel) {
	o.Proxy = &v
}

// GetResponseProcessors returns the ResponseProcessors field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetResponseProcessors() []ResponseProcessorModel {
	if o == nil || o.ResponseProcessors == nil {
		var ret []ResponseProcessorModel
		return ret
	}
	return o.ResponseProcessors
}

// GetResponseProcessorsOk returns a tuple with the ResponseProcessors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetResponseProcessorsOk() ([]ResponseProcessorModel, bool) {
	if o == nil || o.ResponseProcessors == nil {
		return nil, false
	}
	return o.ResponseProcessors, true
}

// HasResponseProcessors returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasResponseProcessors() bool {
	if o != nil && o.ResponseProcessors != nil {
		return true
	}

	return false
}

// SetResponseProcessors gets a reference to the given []ResponseProcessorModel and assigns it to the ResponseProcessors field.
func (o *APIDefinitionModel) SetResponseProcessors(v []ResponseProcessorModel) {
	o.ResponseProcessors = v
}

// GetSessionLifetime returns the SessionLifetime field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetSessionLifetime() int64 {
	if o == nil || o.SessionLifetime == nil {
		var ret int64
		return ret
	}
	return *o.SessionLifetime
}

// GetSessionLifetimeOk returns a tuple with the SessionLifetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetSessionLifetimeOk() (*int64, bool) {
	if o == nil || o.SessionLifetime == nil {
		return nil, false
	}
	return o.SessionLifetime, true
}

// HasSessionLifetime returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasSessionLifetime() bool {
	if o != nil && o.SessionLifetime != nil {
		return true
	}

	return false
}

// SetSessionLifetime gets a reference to the given int64 and assigns it to the SessionLifetime field.
func (o *APIDefinitionModel) SetSessionLifetime(v int64) {
	o.SessionLifetime = &v
}

// GetSessionProvider returns the SessionProvider field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetSessionProvider() SessionProviderMetaModel {
	if o == nil || o.SessionProvider == nil {
		var ret SessionProviderMetaModel
		return ret
	}
	return *o.SessionProvider
}

// GetSessionProviderOk returns a tuple with the SessionProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetSessionProviderOk() (*SessionProviderMetaModel, bool) {
	if o == nil || o.SessionProvider == nil {
		return nil, false
	}
	return o.SessionProvider, true
}

// HasSessionProvider returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasSessionProvider() bool {
	if o != nil && o.SessionProvider != nil {
		return true
	}

	return false
}

// SetSessionProvider gets a reference to the given SessionProviderMetaModel and assigns it to the SessionProvider field.
func (o *APIDefinitionModel) SetSessionProvider(v SessionProviderMetaModel) {
	o.SessionProvider = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetSlug() string {
	if o == nil || o.Slug == nil {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetSlugOk() (*string, bool) {
	if o == nil || o.Slug == nil {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasSlug() bool {
	if o != nil && o.Slug != nil {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *APIDefinitionModel) SetSlug(v string) {
	o.Slug = &v
}

// GetStripAuthData returns the StripAuthData field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetStripAuthData() bool {
	if o == nil || o.StripAuthData == nil {
		var ret bool
		return ret
	}
	return *o.StripAuthData
}

// GetStripAuthDataOk returns a tuple with the StripAuthData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetStripAuthDataOk() (*bool, bool) {
	if o == nil || o.StripAuthData == nil {
		return nil, false
	}
	return o.StripAuthData, true
}

// HasStripAuthData returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasStripAuthData() bool {
	if o != nil && o.StripAuthData != nil {
		return true
	}

	return false
}

// SetStripAuthData gets a reference to the given bool and assigns it to the StripAuthData field.
func (o *APIDefinitionModel) SetStripAuthData(v bool) {
	o.StripAuthData = &v
}

// GetTagHeaders returns the TagHeaders field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetTagHeaders() []string {
	if o == nil || o.TagHeaders == nil {
		var ret []string
		return ret
	}
	return o.TagHeaders
}

// GetTagHeadersOk returns a tuple with the TagHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetTagHeadersOk() ([]string, bool) {
	if o == nil || o.TagHeaders == nil {
		return nil, false
	}
	return o.TagHeaders, true
}

// HasTagHeaders returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasTagHeaders() bool {
	if o != nil && o.TagHeaders != nil {
		return true
	}

	return false
}

// SetTagHeaders gets a reference to the given []string and assigns it to the TagHeaders field.
func (o *APIDefinitionModel) SetTagHeaders(v []string) {
	o.TagHeaders = v
}

// GetUpstreamCertificates returns the UpstreamCertificates field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetUpstreamCertificates() map[string]string {
	if o == nil || o.UpstreamCertificates == nil {
		var ret map[string]string
		return ret
	}
	return *o.UpstreamCertificates
}

// GetUpstreamCertificatesOk returns a tuple with the UpstreamCertificates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetUpstreamCertificatesOk() (*map[string]string, bool) {
	if o == nil || o.UpstreamCertificates == nil {
		return nil, false
	}
	return o.UpstreamCertificates, true
}

// HasUpstreamCertificates returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasUpstreamCertificates() bool {
	if o != nil && o.UpstreamCertificates != nil {
		return true
	}

	return false
}

// SetUpstreamCertificates gets a reference to the given map[string]string and assigns it to the UpstreamCertificates field.
func (o *APIDefinitionModel) SetUpstreamCertificates(v map[string]string) {
	o.UpstreamCertificates = &v
}

// GetUptimeTests returns the UptimeTests field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetUptimeTests() APIDefinitionUptimeTestsModelModel {
	if o == nil || o.UptimeTests == nil {
		var ret APIDefinitionUptimeTestsModelModel
		return ret
	}
	return *o.UptimeTests
}

// GetUptimeTestsOk returns a tuple with the UptimeTests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetUptimeTestsOk() (*APIDefinitionUptimeTestsModelModel, bool) {
	if o == nil || o.UptimeTests == nil {
		return nil, false
	}
	return o.UptimeTests, true
}

// HasUptimeTests returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasUptimeTests() bool {
	if o != nil && o.UptimeTests != nil {
		return true
	}

	return false
}

// SetUptimeTests gets a reference to the given APIDefinitionUptimeTestsModelModel and assigns it to the UptimeTests field.
func (o *APIDefinitionModel) SetUptimeTests(v APIDefinitionUptimeTestsModelModel) {
	o.UptimeTests = &v
}

// GetUseBasicAuth returns the UseBasicAuth field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetUseBasicAuth() bool {
	if o == nil || o.UseBasicAuth == nil {
		var ret bool
		return ret
	}
	return *o.UseBasicAuth
}

// GetUseBasicAuthOk returns a tuple with the UseBasicAuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetUseBasicAuthOk() (*bool, bool) {
	if o == nil || o.UseBasicAuth == nil {
		return nil, false
	}
	return o.UseBasicAuth, true
}

// HasUseBasicAuth returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasUseBasicAuth() bool {
	if o != nil && o.UseBasicAuth != nil {
		return true
	}

	return false
}

// SetUseBasicAuth gets a reference to the given bool and assigns it to the UseBasicAuth field.
func (o *APIDefinitionModel) SetUseBasicAuth(v bool) {
	o.UseBasicAuth = &v
}

// GetUseKeyless returns the UseKeyless field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetUseKeyless() bool {
	if o == nil || o.UseKeyless == nil {
		var ret bool
		return ret
	}
	return *o.UseKeyless
}

// GetUseKeylessOk returns a tuple with the UseKeyless field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetUseKeylessOk() (*bool, bool) {
	if o == nil || o.UseKeyless == nil {
		return nil, false
	}
	return o.UseKeyless, true
}

// HasUseKeyless returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasUseKeyless() bool {
	if o != nil && o.UseKeyless != nil {
		return true
	}

	return false
}

// SetUseKeyless gets a reference to the given bool and assigns it to the UseKeyless field.
func (o *APIDefinitionModel) SetUseKeyless(v bool) {
	o.UseKeyless = &v
}

// GetUseMutualTlsAuth returns the UseMutualTlsAuth field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetUseMutualTlsAuth() bool {
	if o == nil || o.UseMutualTlsAuth == nil {
		var ret bool
		return ret
	}
	return *o.UseMutualTlsAuth
}

// GetUseMutualTlsAuthOk returns a tuple with the UseMutualTlsAuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetUseMutualTlsAuthOk() (*bool, bool) {
	if o == nil || o.UseMutualTlsAuth == nil {
		return nil, false
	}
	return o.UseMutualTlsAuth, true
}

// HasUseMutualTlsAuth returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasUseMutualTlsAuth() bool {
	if o != nil && o.UseMutualTlsAuth != nil {
		return true
	}

	return false
}

// SetUseMutualTlsAuth gets a reference to the given bool and assigns it to the UseMutualTlsAuth field.
func (o *APIDefinitionModel) SetUseMutualTlsAuth(v bool) {
	o.UseMutualTlsAuth = &v
}

// GetUseOauth2 returns the UseOauth2 field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetUseOauth2() bool {
	if o == nil || o.UseOauth2 == nil {
		var ret bool
		return ret
	}
	return *o.UseOauth2
}

// GetUseOauth2Ok returns a tuple with the UseOauth2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetUseOauth2Ok() (*bool, bool) {
	if o == nil || o.UseOauth2 == nil {
		return nil, false
	}
	return o.UseOauth2, true
}

// HasUseOauth2 returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasUseOauth2() bool {
	if o != nil && o.UseOauth2 != nil {
		return true
	}

	return false
}

// SetUseOauth2 gets a reference to the given bool and assigns it to the UseOauth2 field.
func (o *APIDefinitionModel) SetUseOauth2(v bool) {
	o.UseOauth2 = &v
}

// GetUseOpenid returns the UseOpenid field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetUseOpenid() bool {
	if o == nil || o.UseOpenid == nil {
		var ret bool
		return ret
	}
	return *o.UseOpenid
}

// GetUseOpenidOk returns a tuple with the UseOpenid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetUseOpenidOk() (*bool, bool) {
	if o == nil || o.UseOpenid == nil {
		return nil, false
	}
	return o.UseOpenid, true
}

// HasUseOpenid returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasUseOpenid() bool {
	if o != nil && o.UseOpenid != nil {
		return true
	}

	return false
}

// SetUseOpenid gets a reference to the given bool and assigns it to the UseOpenid field.
func (o *APIDefinitionModel) SetUseOpenid(v bool) {
	o.UseOpenid = &v
}

// GetUseStandardAuth returns the UseStandardAuth field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetUseStandardAuth() bool {
	if o == nil || o.UseStandardAuth == nil {
		var ret bool
		return ret
	}
	return *o.UseStandardAuth
}

// GetUseStandardAuthOk returns a tuple with the UseStandardAuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetUseStandardAuthOk() (*bool, bool) {
	if o == nil || o.UseStandardAuth == nil {
		return nil, false
	}
	return o.UseStandardAuth, true
}

// HasUseStandardAuth returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasUseStandardAuth() bool {
	if o != nil && o.UseStandardAuth != nil {
		return true
	}

	return false
}

// SetUseStandardAuth gets a reference to the given bool and assigns it to the UseStandardAuth field.
func (o *APIDefinitionModel) SetUseStandardAuth(v bool) {
	o.UseStandardAuth = &v
}

// GetVersionData returns the VersionData field value if set, zero value otherwise.
func (o *APIDefinitionModel) GetVersionData() APIDefinitionVersionDataModelModel {
	if o == nil || o.VersionData == nil {
		var ret APIDefinitionVersionDataModelModel
		return ret
	}
	return *o.VersionData
}

// GetVersionDataOk returns a tuple with the VersionData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionModel) GetVersionDataOk() (*APIDefinitionVersionDataModelModel, bool) {
	if o == nil || o.VersionData == nil {
		return nil, false
	}
	return o.VersionData, true
}

// HasVersionData returns a boolean if a field has been set.
func (o *APIDefinitionModel) HasVersionData() bool {
	if o != nil && o.VersionData != nil {
		return true
	}

	return false
}

// SetVersionData gets a reference to the given APIDefinitionVersionDataModelModel and assigns it to the VersionData field.
func (o *APIDefinitionModel) SetVersionData(v APIDefinitionVersionDataModelModel) {
	o.VersionData = &v
}

func (o APIDefinitionModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.CORS != nil {
		toSerialize["CORS"] = o.CORS
	}
	if o.Active != nil {
		toSerialize["active"] = o.Active
	}
	if o.AllowedIps != nil {
		toSerialize["allowed_ips"] = o.AllowedIps
	}
	if o.ApiId != nil {
		toSerialize["api_id"] = o.ApiId
	}
	if o.Auth != nil {
		toSerialize["auth"] = o.Auth
	}
	if o.AuthProvider != nil {
		toSerialize["auth_provider"] = o.AuthProvider
	}
	if o.BaseIdentityProvidedBy != nil {
		toSerialize["base_identity_provided_by"] = o.BaseIdentityProvidedBy
	}
	if o.BasicAuth != nil {
		toSerialize["basic_auth"] = o.BasicAuth
	}
	if o.BlacklistedIps != nil {
		toSerialize["blacklisted_ips"] = o.BlacklistedIps
	}
	if o.CacheOptions != nil {
		toSerialize["cache_options"] = o.CacheOptions
	}
	if o.Certificates != nil {
		toSerialize["certificates"] = o.Certificates
	}
	if o.ClientCertificates != nil {
		toSerialize["client_certificates"] = o.ClientCertificates
	}
	if o.ConfigData != nil {
		toSerialize["config_data"] = o.ConfigData
	}
	if o.CustomMiddleware != nil {
		toSerialize["custom_middleware"] = o.CustomMiddleware
	}
	if o.CustomMiddlewareBundle != nil {
		toSerialize["custom_middleware_bundle"] = o.CustomMiddlewareBundle
	}
	if o.Definition != nil {
		toSerialize["definition"] = o.Definition
	}
	if o.DisableQuota != nil {
		toSerialize["disable_quota"] = o.DisableQuota
	}
	if o.DisableRateLimit != nil {
		toSerialize["disable_rate_limit"] = o.DisableRateLimit
	}
	if o.DoNotTrack != nil {
		toSerialize["do_not_track"] = o.DoNotTrack
	}
	if o.Domain != nil {
		toSerialize["domain"] = o.Domain
	}
	if o.DontSetQuotaOnCreate != nil {
		toSerialize["dont_set_quota_on_create"] = o.DontSetQuotaOnCreate
	}
	if o.EnableBatchRequestSupport != nil {
		toSerialize["enable_batch_request_support"] = o.EnableBatchRequestSupport
	}
	if o.EnableContextVars != nil {
		toSerialize["enable_context_vars"] = o.EnableContextVars
	}
	if o.EnableCoprocessAuth != nil {
		toSerialize["enable_coprocess_auth"] = o.EnableCoprocessAuth
	}
	if o.EnableIpBlacklisting != nil {
		toSerialize["enable_ip_blacklisting"] = o.EnableIpBlacklisting
	}
	if o.EnableIpWhitelisting != nil {
		toSerialize["enable_ip_whitelisting"] = o.EnableIpWhitelisting
	}
	if o.EnableJwt != nil {
		toSerialize["enable_jwt"] = o.EnableJwt
	}
	if o.EnableSignatureChecking != nil {
		toSerialize["enable_signature_checking"] = o.EnableSignatureChecking
	}
	if o.EventHandlers != nil {
		toSerialize["event_handlers"] = o.EventHandlers
	}
	if o.ExpireAnalyticsAfter != nil {
		toSerialize["expire_analytics_after"] = o.ExpireAnalyticsAfter
	}
	if o.GlobalRateLimit != nil {
		toSerialize["global_rate_limit"] = o.GlobalRateLimit
	}
	if o.HmacAllowedAlgorithms != nil {
		toSerialize["hmac_allowed_algorithms"] = o.HmacAllowedAlgorithms
	}
	if o.HmacAllowedClockSkew != nil {
		toSerialize["hmac_allowed_clock_skew"] = o.HmacAllowedClockSkew
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Internal != nil {
		toSerialize["internal"] = o.Internal
	}
	if o.JwtClientBaseField != nil {
		toSerialize["jwt_client_base_field"] = o.JwtClientBaseField
	}
	if o.JwtExpiresAtValidationSkew != nil {
		toSerialize["jwt_expires_at_validation_skew"] = o.JwtExpiresAtValidationSkew
	}
	if o.JwtIdentityBaseField != nil {
		toSerialize["jwt_identity_base_field"] = o.JwtIdentityBaseField
	}
	if o.JwtIssuedAtValidationSkew != nil {
		toSerialize["jwt_issued_at_validation_skew"] = o.JwtIssuedAtValidationSkew
	}
	if o.JwtNotBeforeValidationSkew != nil {
		toSerialize["jwt_not_before_validation_skew"] = o.JwtNotBeforeValidationSkew
	}
	if o.JwtPolicyFieldName != nil {
		toSerialize["jwt_policy_field_name"] = o.JwtPolicyFieldName
	}
	if o.JwtScopeClaimName != nil {
		toSerialize["jwt_scope_claim_name"] = o.JwtScopeClaimName
	}
	if o.JwtScopeToPolicyMapping != nil {
		toSerialize["jwt_scope_to_policy_mapping"] = o.JwtScopeToPolicyMapping
	}
	if o.JwtSigningMethod != nil {
		toSerialize["jwt_signing_method"] = o.JwtSigningMethod
	}
	if o.JwtSkipKid != nil {
		toSerialize["jwt_skip_kid"] = o.JwtSkipKid
	}
	if o.JwtSource != nil {
		toSerialize["jwt_source"] = o.JwtSource
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Notifications != nil {
		toSerialize["notifications"] = o.Notifications
	}
	if o.OauthMeta != nil {
		toSerialize["oauth_meta"] = o.OauthMeta
	}
	if o.OpenidOptions != nil {
		toSerialize["openid_options"] = o.OpenidOptions
	}
	if o.OrgId != nil {
		toSerialize["org_id"] = o.OrgId
	}
	if o.PinnedPublicKeys != nil {
		toSerialize["pinned_public_keys"] = o.PinnedPublicKeys
	}
	if o.Proxy != nil {
		toSerialize["proxy"] = o.Proxy
	}
	if o.ResponseProcessors != nil {
		toSerialize["response_processors"] = o.ResponseProcessors
	}
	if o.SessionLifetime != nil {
		toSerialize["session_lifetime"] = o.SessionLifetime
	}
	if o.SessionProvider != nil {
		toSerialize["session_provider"] = o.SessionProvider
	}
	if o.Slug != nil {
		toSerialize["slug"] = o.Slug
	}
	if o.StripAuthData != nil {
		toSerialize["strip_auth_data"] = o.StripAuthData
	}
	if o.TagHeaders != nil {
		toSerialize["tag_headers"] = o.TagHeaders
	}
	if o.UpstreamCertificates != nil {
		toSerialize["upstream_certificates"] = o.UpstreamCertificates
	}
	if o.UptimeTests != nil {
		toSerialize["uptime_tests"] = o.UptimeTests
	}
	if o.UseBasicAuth != nil {
		toSerialize["use_basic_auth"] = o.UseBasicAuth
	}
	if o.UseKeyless != nil {
		toSerialize["use_keyless"] = o.UseKeyless
	}
	if o.UseMutualTlsAuth != nil {
		toSerialize["use_mutual_tls_auth"] = o.UseMutualTlsAuth
	}
	if o.UseOauth2 != nil {
		toSerialize["use_oauth2"] = o.UseOauth2
	}
	if o.UseOpenid != nil {
		toSerialize["use_openid"] = o.UseOpenid
	}
	if o.UseStandardAuth != nil {
		toSerialize["use_standard_auth"] = o.UseStandardAuth
	}
	if o.VersionData != nil {
		toSerialize["version_data"] = o.VersionData
	}
	return json.Marshal(toSerialize)
}

type NullableAPIDefinitionModel struct {
	value *APIDefinitionModel
	isSet bool
}

func (v NullableAPIDefinitionModel) Get() *APIDefinitionModel {
	return v.value
}

func (v *NullableAPIDefinitionModel) Set(val *APIDefinitionModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIDefinitionModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIDefinitionModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIDefinitionModel(val *APIDefinitionModel) *NullableAPIDefinitionModel {
	return &NullableAPIDefinitionModel{value: val, isSet: true}
}

func (v NullableAPIDefinitionModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIDefinitionModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


