/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 4.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gate

import (
	"encoding/json"
)

// APIDefinitionUptimeTestsModel struct for APIDefinitionUptimeTestsModel
type APIDefinitionUptimeTestsModel struct {
	CheckList []HostCheckObjectModelModel `json:"check_list,omitempty"`
	Config *APIDefinitionUptimeTestsConfigModelModel `json:"config,omitempty"`
}

// NewAPIDefinitionUptimeTestsModel instantiates a new APIDefinitionUptimeTestsModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIDefinitionUptimeTestsModel() *APIDefinitionUptimeTestsModel {
	this := APIDefinitionUptimeTestsModel{}
	return &this
}

// NewAPIDefinitionUptimeTestsModelWithDefaults instantiates a new APIDefinitionUptimeTestsModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIDefinitionUptimeTestsModelWithDefaults() *APIDefinitionUptimeTestsModel {
	this := APIDefinitionUptimeTestsModel{}
	return &this
}

// GetCheckList returns the CheckList field value if set, zero value otherwise.
func (o *APIDefinitionUptimeTestsModel) GetCheckList() []HostCheckObjectModelModel {
	if o == nil || o.CheckList == nil {
		var ret []HostCheckObjectModelModel
		return ret
	}
	return o.CheckList
}

// GetCheckListOk returns a tuple with the CheckList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionUptimeTestsModel) GetCheckListOk() ([]HostCheckObjectModelModel, bool) {
	if o == nil || o.CheckList == nil {
		return nil, false
	}
	return o.CheckList, true
}

// HasCheckList returns a boolean if a field has been set.
func (o *APIDefinitionUptimeTestsModel) HasCheckList() bool {
	if o != nil && o.CheckList != nil {
		return true
	}

	return false
}

// SetCheckList gets a reference to the given []HostCheckObjectModelModel and assigns it to the CheckList field.
func (o *APIDefinitionUptimeTestsModel) SetCheckList(v []HostCheckObjectModelModel) {
	o.CheckList = v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *APIDefinitionUptimeTestsModel) GetConfig() APIDefinitionUptimeTestsConfigModelModel {
	if o == nil || o.Config == nil {
		var ret APIDefinitionUptimeTestsConfigModelModel
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionUptimeTestsModel) GetConfigOk() (*APIDefinitionUptimeTestsConfigModelModel, bool) {
	if o == nil || o.Config == nil {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *APIDefinitionUptimeTestsModel) HasConfig() bool {
	if o != nil && o.Config != nil {
		return true
	}

	return false
}

// SetConfig gets a reference to the given APIDefinitionUptimeTestsConfigModelModel and assigns it to the Config field.
func (o *APIDefinitionUptimeTestsModel) SetConfig(v APIDefinitionUptimeTestsConfigModelModel) {
	o.Config = &v
}

func (o APIDefinitionUptimeTestsModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CheckList != nil {
		toSerialize["check_list"] = o.CheckList
	}
	if o.Config != nil {
		toSerialize["config"] = o.Config
	}
	return json.Marshal(toSerialize)
}

type NullableAPIDefinitionUptimeTestsModel struct {
	value *APIDefinitionUptimeTestsModel
	isSet bool
}

func (v NullableAPIDefinitionUptimeTestsModel) Get() *APIDefinitionUptimeTestsModel {
	return v.value
}

func (v *NullableAPIDefinitionUptimeTestsModel) Set(val *APIDefinitionUptimeTestsModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIDefinitionUptimeTestsModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIDefinitionUptimeTestsModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIDefinitionUptimeTestsModel(val *APIDefinitionUptimeTestsModel) *NullableAPIDefinitionUptimeTestsModel {
	return &NullableAPIDefinitionUptimeTestsModel{value: val, isSet: true}
}

func (v NullableAPIDefinitionUptimeTestsModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIDefinitionUptimeTestsModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


