/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 4.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gate

import (
	"encoding/json"
)

// ServerVariableModel struct for ServerVariableModel
type ServerVariableModel struct {
	Enum []string `json:"enum,omitempty"`
	Default string `json:"default"`
	Description *string `json:"description,omitempty"`
}

// NewServerVariableModel instantiates a new ServerVariableModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerVariableModel(default_ string) *ServerVariableModel {
	this := ServerVariableModel{}
	this.Default = default_
	return &this
}

// NewServerVariableModelWithDefaults instantiates a new ServerVariableModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerVariableModelWithDefaults() *ServerVariableModel {
	this := ServerVariableModel{}
	return &this
}

// GetEnum returns the Enum field value if set, zero value otherwise.
func (o *ServerVariableModel) GetEnum() []string {
	if o == nil || o.Enum == nil {
		var ret []string
		return ret
	}
	return o.Enum
}

// GetEnumOk returns a tuple with the Enum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerVariableModel) GetEnumOk() ([]string, bool) {
	if o == nil || o.Enum == nil {
		return nil, false
	}
	return o.Enum, true
}

// HasEnum returns a boolean if a field has been set.
func (o *ServerVariableModel) HasEnum() bool {
	if o != nil && o.Enum != nil {
		return true
	}

	return false
}

// SetEnum gets a reference to the given []string and assigns it to the Enum field.
func (o *ServerVariableModel) SetEnum(v []string) {
	o.Enum = v
}

// GetDefault returns the Default field value
func (o *ServerVariableModel) GetDefault() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value
// and a boolean to check if the value has been set.
func (o *ServerVariableModel) GetDefaultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Default, true
}

// SetDefault sets field value
func (o *ServerVariableModel) SetDefault(v string) {
	o.Default = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ServerVariableModel) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerVariableModel) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ServerVariableModel) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ServerVariableModel) SetDescription(v string) {
	o.Description = &v
}

func (o ServerVariableModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Enum != nil {
		toSerialize["enum"] = o.Enum
	}
	if true {
		toSerialize["default"] = o.Default
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableServerVariableModel struct {
	value *ServerVariableModel
	isSet bool
}

func (v NullableServerVariableModel) Get() *ServerVariableModel {
	return v.value
}

func (v *NullableServerVariableModel) Set(val *ServerVariableModel) {
	v.value = val
	v.isSet = true
}

func (v NullableServerVariableModel) IsSet() bool {
	return v.isSet
}

func (v *NullableServerVariableModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerVariableModel(val *ServerVariableModel) *NullableServerVariableModel {
	return &NullableServerVariableModel{value: val, isSet: true}
}

func (v NullableServerVariableModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerVariableModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


